# 6. Working with text data

In [1]:
import numpy as np
import pandas as pd

In [2]:
inspections = pd.read_csv("chicago_food_inspections.csv")
inspections

                                      Name             Risk
0               MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                              JETS PIZZA   Risk 2 (Medium)
2                               ROOM 1520      Risk 3 (Low)
3                MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                            CHARTWELLS       Risk 1 (High)
...                                    ...              ...
153805                         WOLCOTT'S      Risk 1 (High)
153806     DUNKIN DONUTS/BASKIN-ROBBINS     Risk 2 (Medium)
153807                           Cafe 608     Risk 1 (High)
153808                        mr.daniel's     Risk 1 (High)
153809                         TEMPO CAFE     Risk 1 (High)

[153810 rows x 2 columns]

In [3]:
inspections

                                      Name             Risk
0               MARRIOT MARQUIS CHICAGO       Risk 1 (High)
1                              JETS PIZZA   Risk 2 (Medium)
2                               ROOM 1520      Risk 3 (Low)
3                MARRIOT MARQUIS CHICAGO      Risk 1 (High)
4                            CHARTWELLS       Risk 1 (High)
...                                    ...              ...
153805                         WOLCOTT'S      Risk 1 (High)
153806     DUNKIN DONUTS/BASKIN-ROBBINS     Risk 2 (Medium)
153807                           Cafe 608     Risk 1 (High)
153808                        mr.daniel's     Risk 1 (High)
153809                         TEMPO CAFE     Risk 1 (High)

[153810 rows x 2 columns]

In [4]:
inspections["Name"].head().values

array([' MARRIOT MARQUIS CHICAGO   ', ' JETS PIZZA ', '   ROOM 1520 ',
       '  MARRIOT MARQUIS CHICAGO  ', ' CHARTWELLS   '], dtype=object)

In [5]:
inspections["Name"] = inspections["Name"].str.strip()

In [6]:
inspections["Name"].head().values

array(['MARRIOT MARQUIS CHICAGO', 'JETS PIZZA', 'ROOM 1520',
       'MARRIOT MARQUIS CHICAGO', 'CHARTWELLS'], dtype=object)

In [7]:
inspections.columns

Index(['Name', 'Risk'], dtype='object')

In [8]:
for column in inspections.columns:
    inspections[column] = inspections[column].str.strip()

In [9]:
inspections["Name"].str.title().head()

0    Marriot Marquis Chicago
1                 Jets Pizza
2                  Room 1520
3    Marriot Marquis Chicago
4                 Chartwells
Name: Name, dtype: object

In [10]:
inspections["Risk"].head()

0      Risk 1 (High)
1    Risk 2 (Medium)
2       Risk 3 (Low)
3      Risk 1 (High)
4      Risk 1 (High)
Name: Risk, dtype: object

In [11]:
inspections["Risk"].value_counts()

Risk
Risk 1 (High)      107351
Risk 2 (Medium)     31845
Risk 3 (Low)        14529
All                    19
Name: count, dtype: int64

In [12]:
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan],
      dtype=object)

In [13]:
inspections = inspections.dropna(subset = ["Risk"])

In [14]:
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All'],
      dtype=object)

In [15]:
inspections = inspections.replace(to_replace = "All", value="Risk 4 (Extreme)")

In [16]:
inspections["Risk"].unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)',
       'Risk 4 (Extreme)'], dtype=object)

In [17]:
# pulls the characters from index position 5 up to (but not including) index position 6
inspections["Risk"].str.slice(5,6).head()

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [18]:
# using list slicing
inspections["Risk"].str[5:6].head()

0    1
1    2
2    3
3    1
4    1
Name: Risk, dtype: object

In [19]:
# pull the characters from index position 8 to the end of each string
inspections["Risk"].str.slice(8).head()

0      High)
1    Medium)
2       Low)
3      High)
4      High)
Name: Risk, dtype: object

In [20]:
# making use of -1
inspections["Risk"].str.slice(8, -1).head()

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [21]:
inspections["Risk"].str.slice(8).str.replace(")", "").head()

0      High
1    Medium
2       Low
3      High
4      High
Name: Risk, dtype: object

In [22]:
inspections["Name"].str.lower().str.contains("pizza").head()

0    False
1     True
2    False
3    False
4    False
Name: Name, dtype: bool

In [23]:
has_pizza = inspections["Name"].str.lower().str.contains("pizza")
inspections[has_pizza]

                                    Name             Risk
1                             JETS PIZZA  Risk 2 (Medium)
19         NANCY'S HOME OF STUFFED PIZZA    Risk 1 (High)
27            NARY'S GRILL & PIZZA ,INC.    Risk 1 (High)
29                   NARYS GRILL & PIZZA    Risk 1 (High)
68                         COLUTAS PIZZA    Risk 1 (High)
...                                  ...              ...
153756       ANGELO'S STUFFED PIZZA CORP    Risk 1 (High)
153764                COCHIAROS PIZZA #2    Risk 1 (High)
153772  FERNANDO'S MEXICAN GRILL & PIZZA    Risk 1 (High)
153788            REGGIO'S PIZZA EXPRESS    Risk 1 (High)
153801        State Street Pizza Company    Risk 1 (High)

[3992 rows x 2 columns]

In [24]:
starts_with_tacos = inspections["Name"].str.lower().str.startswith("tacos")
inspections[starts_with_tacos]

                         Name           Risk
69               TACOS NIETOS  Risk 1 (High)
556       TACOS EL TIO 2 INC.  Risk 1 (High)
675          TACOS DON GABINO  Risk 1 (High)
958       TACOS EL TIO 2 INC.  Risk 1 (High)
1036      TACOS EL TIO 2 INC.  Risk 1 (High)
...                       ...            ...
143587          TACOS DE LUNA  Risk 1 (High)
144026           TACOS GARCIA  Risk 1 (High)
146174        Tacos Place's 1  Risk 1 (High)
147810  TACOS MARIO'S LIMITED  Risk 1 (High)
151191            TACOS REYNA  Risk 1 (High)

[105 rows x 2 columns]

In [25]:
ends_with_tacos = inspections["Name"].str.lower().str.endswith("tacos")
inspections[ends_with_tacos]

                   Name           Risk
382        LAZO'S TACOS  Risk 1 (High)
569        LAZO'S TACOS  Risk 1 (High)
2652       FLYING TACOS   Risk 3 (Low)
3250       JONY'S TACOS  Risk 1 (High)
3812       PACO'S TACOS  Risk 1 (High)
...                 ...            ...
151121      REYES TACOS  Risk 1 (High)
151318   EL MACHO TACOS  Risk 1 (High)
151801   EL MACHO TACOS  Risk 1 (High)
153087  RAYMOND'S TACOS  Risk 1 (High)
153504        MIS TACOS  Risk 1 (High)

[304 rows x 2 columns]

In [26]:
customers = pd.read_csv("customers.csv")
customers.head()

                  Name                                            Address
0        Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1    Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2      Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3  Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4       Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...

In [27]:
customers["Name"].str.len().head()

0    13
1    17
2    15
3    19
4    14
Name: Name, dtype: int64

In [28]:
 customers["Name"].str.split(" ").head()

0           [Frank, Manning]
1       [Elizabeth, Johnson]
2         [Donald, Stephens]
3    [Michael, Vincent, III]
4          [Jasmine, Zamora]
Name: Name, dtype: object

In [29]:
customers["Name"].str.split(pat=" ", n=1).head()

0          [Frank, Manning]
1      [Elizabeth, Johnson]
2        [Donald, Stephens]
3    [Michael, Vincent III]
4         [Jasmine, Zamora]
Name: Name, dtype: object

In [30]:
customers["Name"].str.split(pat=" ", n=1).str.get(0).head()

0        Frank
1    Elizabeth
2       Donald
3      Michael
4      Jasmine
Name: Name, dtype: object

In [31]:
customers["Name"].str.split(pat=" ", n=1).str.get(1).head()

0        Manning
1        Johnson
2       Stephens
3    Vincent III
4         Zamora
Name: Name, dtype: object

In [32]:
customers["Name"].str.split(pat=" ", n=1).str.get(-1).head()

0        Manning
1        Johnson
2       Stephens
3    Vincent III
4         Zamora
Name: Name, dtype: object

In [33]:
customers["Name"].str.split(pat=" ", n=1, expand=True).head()

           0            1
0      Frank      Manning
1  Elizabeth      Johnson
2     Donald     Stephens
3    Michael  Vincent III
4    Jasmine       Zamora

In [34]:
customers[["First Name", "Last Name"]] = customers["Name"].str.split(pat=" ", n=1, expand=True)
customers.head()

,Name,Address,First Name,Last Name
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",Frank,Manning
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",Elizabeth,Johnson
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",Donald,Stephens
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",Michael,Vincent III
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",Jasmine,Zamora

In [36]:
#customers.columns
customers = customers.drop(labels = "Name", axis="columns")
customers.head()

                                             Address First Name    Last Name
0  6461 Quinn Groves, East Matthew, New Hampshire...      Frank      Manning
1  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...  Elizabeth      Johnson
2  19120 Fleming Manors, Prestonstad, Montana, 23495     Donald     Stephens
3       441 Olivia Creek, Jimmymouth, Georgia, 82991    Michael  Vincent III
4  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...    Jasmine       Zamora