## 6.6 Coding challenge

### 6.6.1 Problems

Our customers data set includes an Address column. Each address consists of a street,
a city, a state, and a zip code. Your challenge is to separate these four values; assign
them to new Street, City, State, and Zip columns; and then remove the Address column. 
Give the problem a shot, and then review the solution.

In [1]:
import pandas as pd

In [14]:
customers = pd.read_csv("customers.csv")
customers.head()

                  Name                                            Address
0        Frank Manning  6461 Quinn Groves, East Matthew, New Hampshire...
1    Elizabeth Johnson  1360 Tracey Ports Apt. 419, Kyleport, Vermont,...
2      Donald Stephens  19120 Fleming Manors, Prestonstad, Montana, 23495
3  Michael Vincent III       441 Olivia Creek, Jimmymouth, Georgia, 82991
4       Jasmine Zamora  4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...

In [15]:
customers["Address"].str.split(pat=", ", expand=True)

                               0             1              2      3
0              6461 Quinn Groves  East Matthew  New Hampshire  16656
1     1360 Tracey Ports Apt. 419      Kyleport        Vermont  31924
2           19120 Fleming Manors   Prestonstad        Montana  23495
3               441 Olivia Creek    Jimmymouth        Georgia  82991
4     4246 Chelsey Ford Apt. 310     Karamouth           Utah  76252
...                          ...           ...            ...    ...
9956   762 Andrew Views Apt. 254    North Paul     New Mexico  28889
9957    44188 Day Crest Apt. 901   Lake Marcia          Maine  37378
9958      73015 Michelle Squares   Watsonville  West Virginia  03933
9959            129 Keith Greens     Haleyfurt       Oklahoma  98916
9960          355 Griffin Valley     Davidtown     New Mexico  17581

[9961 rows x 4 columns]

In [16]:
customers[["Street", "City", "State", "Zip"]] = customers["Address"].str.split(pat=",", expand=True)
customers.head()

,Name,Address,Street,City,State,Zip
0,Frank Manning,"6461 Quinn Groves, East Matthew, New Hampshire...",6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,"1360 Tracey Ports Apt. 419, Kyleport, Vermont,...",1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,"19120 Fleming Manors, Prestonstad, Montana, 23495",19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,"441 Olivia Creek, Jimmymouth, Georgia, 82991",441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,"4246 Chelsey Ford Apt. 310, Karamouth, Utah, 7...",4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252

In [17]:
customers = customers.drop(labels="Address", axis="columns")
customers.head()

,Name,Street,City,State,Zip
0,Frank Manning,6461 Quinn Groves,East Matthew,New Hampshire,16656
1,Elizabeth Johnson,1360 Tracey Ports Apt. 419,Kyleport,Vermont,31924
2,Donald Stephens,19120 Fleming Manors,Prestonstad,Montana,23495
3,Michael Vincent III,441 Olivia Creek,Jimmymouth,Georgia,82991
4,Jasmine Zamora,4246 Chelsey Ford Apt. 310,Karamouth,Utah,76252