# Chapter 5. Filtering a DataFrame

In [1]:
import pandas as pd

## 5.1 Optimizing a data set for memory use

In [2]:
pd.read_csv("employees.csv")

     First Name  Gender Start Date    Salary   Mgmt          Team
0       Douglas    Male     8/6/93       NaN   True     Marketing
1        Thomas    Male    3/31/96   61933.0   True           NaN
2         Maria  Female        NaN  130590.0  False       Finance
3         Jerry     NaN     3/4/05  138705.0   True       Finance
4         Larry    Male    1/24/98  101004.0   True            IT
...         ...     ...        ...       ...    ...           ...
996     Phillip    Male    1/31/84   42392.0  False       Finance
997     Russell    Male    5/20/13   96914.0  False       Product
998       Larry    Male    4/20/13   60500.0  False  Business Dev
999      Albert    Male    5/15/12  129949.0   True         Sales
1000        NaN     NaN        NaN       NaN    NaN           NaN

[1001 rows x 6 columns]

In [3]:
# defint a custom date parser
dateparse = lambda x: datetime.strptime(x, "%m/%d/%Y")
pd.read_csv("employees.csv", parse_dates=['Start Date'], date_format=dateparse).head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male     8/6/93       NaN   True  Marketing
1     Thomas    Male    3/31/96   61933.0   True        NaN
2      Maria  Female        NaN  130590.0  False    Finance
3      Jerry     NaN     3/4/05  138705.0   True    Finance
4      Larry    Male    1/24/98  101004.0   True         IT

In [4]:
employees = pd.read_csv("employees.csv", parse_dates=['Start Date'])

C:\Users\lorra\AppData\Local\Temp\ipykernel_40924\295233696.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv("employees.csv", parse_dates=['Start Date'])

In [5]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        933 non-null    object
 5   Team        957 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 47.1+ KB

In [6]:
employees["Mgmt"].astype(bool)

0        True
1        True
2       False
3        True
4        True
        ...
996     False
997     False
998     False
999      True
1000     True
Name: Mgmt, Length: 1001, dtype: bool

In [7]:
employees["Mgmt"] = employees["Mgmt"].astype(bool)

In [8]:
employees.tail()

     First Name Gender Start Date    Salary   Mgmt          Team
996     Phillip   Male 1984-01-31   42392.0  False       Finance
997     Russell   Male 2013-05-20   96914.0  False       Product
998       Larry   Male 2013-04-20   60500.0  False  Business Dev
999      Albert   Male 2012-05-15  129949.0   True         Sales
1000        NaN    NaN        NaT       NaN   True           NaN

In [9]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    object
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      999 non-null    float64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(1), object(3)
memory usage: 40.2+ KB

In [11]:
employees["Salary"].fillna(0).tail()

996      42392.0
997      96914.0
998      60500.0
999     129949.0
1000         0.0
Name: Salary, dtype: float64

In [12]:
employees["Salary"].fillna(0).astype(int).tail()

996      42392
997      96914
998      60500
999     129949
1000         0
Name: Salary, dtype: int64

In [13]:
employees["Salary"] = employees["Salary"].fillna(0).astype(int)

In [14]:
employees.nunique()

First Name    200
Gender          2
Start Date    971
Salary        995
Mgmt            2
Team           10
dtype: int64

In [15]:
employees["Gender"].astype("category")

0         Male
1         Male
2       Female
3          NaN
4         Male
         ...
996       Male
997       Male
998       Male
999       Male
1000       NaN
Name: Gender, Length: 1001, dtype: category
Categories (2, object): ['Female', 'Male']

In [16]:
employees["Gender"] = employees["Gender"].astype("category")

In [17]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    object
dtypes: bool(1), category(1), datetime64[ns](1), int64(1), object(2)
memory usage: 33.5+ KB

In [18]:
employees["Team"] = employees["Team"].astype("category")

In [19]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   First Name  933 non-null    object
 1   Gender      854 non-null    category
 2   Start Date  999 non-null    datetime64[ns]
 3   Salary      1001 non-null   int64
 4   Mgmt        1001 non-null   bool
 5   Team        957 non-null    category
dtypes: bool(1), category(2), datetime64[ns](1), int64(1), object(1)
memory usage: 27.0+ KB

## 5.2 Filtering by a single condition

In [20]:
 employees['First Name'] == "Maria"

0       False
1       False
2        True
3       False
4       False
        ...
996     False
997     False
998     False
999     False
1000    False
Name: First Name, Length: 1001, dtype: bool

In [22]:
 employees[employees['First Name'] == "Maria"]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [23]:
marias = employees['First Name'] == "Maria"
employees[marias]

    First Name  Gender Start Date  Salary   Mgmt          Team
2        Maria  Female        NaT  130590  False       Finance
198      Maria  Female 1990-12-27   36067   True       Product
815      Maria     NaN 1986-01-18  106562  False            HR
844      Maria     NaN 1985-06-19  148857  False         Legal
936      Maria  Female 2003-03-14   96250  False  Business Dev
984      Maria  Female 2011-10-15   43455  False   Engineering

In [24]:
employees["Team"] != "Finance"

0        True
1        True
2       False
3       False
4        True
        ...
996     False
997      True
998      True
999      True
1000     True
Name: Team, Length: 1001, dtype: bool

In [25]:
employees[employees["Team"] != "Finance"]

     First Name  Gender Start Date  Salary   Mgmt          Team
0       Douglas    Male 1993-08-06       0   True     Marketing
1        Thomas    Male 1996-03-31   61933   True           NaN
4         Larry    Male 1998-01-24  101004   True            IT
5        Dennis    Male 1987-04-18  115163  False         Legal
6          Ruby  Female 1987-08-17   65476   True       Product
...         ...     ...        ...     ...    ...           ...
995       Henry     NaN 2014-11-23  132483  False  Distribution
997     Russell    Male 2013-05-20   96914  False       Product
998       Larry    Male 2013-04-20   60500  False  Business Dev
999      Albert    Male 2012-05-15  129949   True         Sales
1000        NaN     NaN        NaT       0   True           NaN

[899 rows x 6 columns]

In [26]:
# retrieve all the managers in the company
employees[employees["Mgmt"]].head()

  First Name  Gender Start Date  Salary  Mgmt       Team
0    Douglas    Male 1993-08-06       0  True  Marketing
1     Thomas    Male 1996-03-31   61933  True        NaN
3      Jerry     NaN 2005-03-04  138705  True    Finance
4      Larry    Male 1998-01-24  101004  True         IT
6       Ruby  Female 1987-08-17   65476  True    Product

In [27]:
high_earners = employees["Salary"] > 100000
high_earners.head()

0    False
1    False
2     True
3     True
4     True
Name: Salary, dtype: bool

In [28]:
employees[high_earners].head()

  First Name  Gender Start Date  Salary   Mgmt          Team
2      Maria  Female        NaT  130590  False       Finance
3      Jerry     NaN 2005-03-04  138705   True       Finance
4      Larry    Male 1998-01-24  101004   True            IT
5     Dennis    Male 1987-04-18  115163  False         Legal
9    Frances  Female 2002-08-08  139852   True  Business Dev

## 5.3 Filtering my multiple conditions

### 5.3.1 The AND condition

In [29]:
is_female = employees["Gender"] == "Female"
in_biz_dev = employees["Team"] == "Business Dev"
employees[is_female & in_biz_dev].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
9     Frances  Female 2002-08-08  139852   True  Business Dev
33       Jean  Female 1993-12-18  119082  False  Business Dev
36     Rachel  Female 2009-02-16  142032  False  Business Dev
38  Stephanie  Female 1986-09-13   36844   True  Business Dev
61     Denise  Female 2001-11-06  106862  False  Business Dev

In [30]:
is_manager = employees["Mgmt"]
employees[is_female & in_biz_dev & is_manager].head()

    First Name  Gender Start Date  Salary  Mgmt          Team
9      Frances  Female 2002-08-08  139852  True  Business Dev
38   Stephanie  Female 1986-09-13   36844  True  Business Dev
66       Nancy  Female 2012-12-15  125250  True  Business Dev
92       Linda  Female 2000-05-25  119009  True  Business Dev
111     Bonnie  Female 1999-12-17   42153  True  Business Dev

### 5.3.2 The OR condition

In [31]:
earning_below_40k = employees["Salary"] < 40000
started_after_2015 = employees["Start Date"] > "2015-01-01"
employees[earning_below_40k | started_after_2015].tail()

     First Name  Gender Start Date  Salary   Mgmt         Team
958      Gloria  Female 1987-10-24   39833  False  Engineering
964       Bruce    Male 1980-05-07   35802   True        Sales
967      Thomas    Male 2016-03-12  105681  False  Engineering
989      Justin     NaN 1991-02-10   38344  False        Legal
1000        NaN     NaN        NaT       0   True          NaN

### 5.3.3 Inversion with ~

In [32]:
employees[employees["Salary"] < 100000].head()

  First Name  Gender Start Date  Salary  Mgmt         Team
0    Douglas    Male 1993-08-06       0  True    Marketing
1     Thomas    Male 1996-03-31   61933  True          NaN
6       Ruby  Female 1987-08-17   65476  True      Product
7        NaN  Female 2015-07-20   45906  True      Finance
8     Angela  Female 2005-11-22   95570  True  Engineering

In [33]:
employees[~(employees["Salary"] >= 100000)].head()

  First Name  Gender Start Date  Salary  Mgmt         Team
0    Douglas    Male 1993-08-06       0  True    Marketing
1     Thomas    Male 1996-03-31   61933  True          NaN
6       Ruby  Female 1987-08-17   65476  True      Product
7        NaN  Female 2015-07-20   45906  True      Finance
8     Angela  Female 2005-11-22   95570  True  Engineering

### 5.3.4 Methods for Booleans

| Operation                | Arithmetic syntax                | Method Syntax                     |
|--------------------------|----------------------------------|-----------------------------------|
| Equality                 | employees["Team"] == "Marketing" | employees["Team"].eq("Marketing") |
| Inequality               | employees["Team"] != "Marketing" | employees["Team"].ne("Marketing") |
| Less than                | employees["Salary"] < 100000     | employees["Salary"].lt(100000)    |
| Less than or equal to    | employees["Salary"] <= 100000    | employees["Salary"].le(100000)    |
| Greater than             |  employees["Salary"] > 100000    | employees["Salary"].gt(100000)    |
| Greater than or equal to | employees["Salary"] >= 100000    | employees["Salary"].ge(100000)    |

## 5.4 Filtering by condition

### 5.4.1 The isin method

In [34]:
sales = employees["Team"] == "Sales"
legal = employees["Team"] == "Legal"
mktg = employees["Team"] == "Marketing"
employees[sales | legal | mktg].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

In [35]:
all_star_teams = ["Sales", "Legal", "Marketing"]
on_all_star_teams = employees["Team"].isin(all_star_teams)
employees[on_all_star_teams].head()

   First Name  Gender Start Date  Salary   Mgmt       Team
0     Douglas    Male 1993-08-06       0   True  Marketing
5      Dennis    Male 1987-04-18  115163  False      Legal
11      Julie  Female 1997-10-26  102508   True      Legal
13       Gary    Male 2008-01-27  109831  False      Sales
20       Lois     NaN 1995-04-22   64714   True      Legal

### 5.4.2 The betweeen method

In [36]:
# identify all employees with a salary between $80,000 and $90,000
higher_than_80 = employees["Salary"] >= 80000
lower_than_90 = employees["Salary"] < 90000
employees[higher_than_80 & lower_than_90].head()

   First Name  Gender Start Date  Salary   Mgmt         Team
19      Donna  Female 2010-07-22   81014  False      Product
31      Joyce     NaN 2005-02-20   88657  False      Product
35    Theresa  Female 2006-10-10   85182  False        Sales
45      Roger    Male 1980-04-17   88010   True        Sales
54       Sara  Female 2007-08-15   83677  False  Engineering

In [37]:
between_80k_and_90k = employees["Salary"].between(80000, 90000)
employees[between_80k_and_90k].head()

   First Name  Gender Start Date  Salary   Mgmt         Team
19      Donna  Female 2010-07-22   81014  False      Product
31      Joyce     NaN 2005-02-20   88657  False      Product
35    Theresa  Female 2006-10-10   85182  False        Sales
45      Roger    Male 1980-04-17   88010   True        Sales
54       Sara  Female 2007-08-15   83677  False  Engineering

In [38]:
# find all employees who started with the company in the 1980's
eighties_folk = employees["Start Date"].between(left="1980-01-01", right="1990-01-01")
employees[eighties_folk].head()

   First Name  Gender Start Date  Salary   Mgmt     Team
5      Dennis    Male 1987-04-18  115163  False    Legal
6        Ruby  Female 1987-08-17   65476   True  Product
10     Louise  Female 1980-08-12   63241   True      NaN
12    Brandon    Male 1980-12-01  112807   True       HR
17      Shawn    Male 1986-12-07  111737  False  Product

In [39]:
# employees where first name starts with "R"
name_starts_with_r = employees["First Name"].between("R", "S")
employees[name_starts_with_r].head()

   First Name  Gender Start Date  Salary   Mgmt          Team
6        Ruby  Female 1987-08-17   65476   True       Product
36     Rachel  Female 2009-02-16  142032  False  Business Dev
45      Roger    Male 1980-04-17   88010   True         Sales
67     Rachel  Female 1999-08-16   51178   True       Finance
78      Robin  Female 1983-06-04  114797   True         Sales

### 5.4.3 The isnull and notnull methods

In [40]:
# missing values
employees.head()

  First Name  Gender Start Date  Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       0   True  Marketing
1     Thomas    Male 1996-03-31   61933   True        NaN
2      Maria  Female        NaT  130590  False    Finance
3      Jerry     NaN 2005-03-04  138705   True    Finance
4      Larry    Male 1998-01-24  101004   True         IT

In [41]:
employees["Team"].isnull().head()

0    False
1     True
2    False
3    False
4    False
Name: Team, dtype: bool

In [42]:
employees[employees["Team"].isnull()].head()

   First Name  Gender Start Date  Salary   Mgmt Team
1      Thomas    Male 1996-03-31   61933   True  NaN
10     Louise  Female 1980-08-12   63241   True  NaN
23        NaN    Male 2012-06-14  125792   True  NaN
32        NaN    Male 1998-08-21  122340   True  NaN
91      James     NaN 2005-01-26  128771  False  NaN

In [43]:
employees[employees["Start Date"].isnull()].head()

     First Name  Gender Start Date  Salary   Mgmt     Team
2         Maria  Female        NaT  130590  False  Finance
1000        NaN     NaN        NaT       0   True      NaN

In [44]:
employees[employees["Team"].notnull()].head()

  First Name  Gender Start Date  Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       0   True  Marketing
2      Maria  Female        NaT  130590  False    Finance
3      Jerry     NaN 2005-03-04  138705   True    Finance
4      Larry    Male 1998-01-24  101004   True         IT
5     Dennis    Male 1987-04-18  115163  False      Legal

In [45]:
# employees missing first name
employees[employees["First Name"].isnull()].head()

   First Name  Gender Start Date  Salary  Mgmt     Team
7         NaN  Female 2015-07-20   45906  True  Finance
23        NaN    Male 2012-06-14  125792  True      NaN
25        NaN    Male 2012-10-08   37076  True       IT
32        NaN    Male 1998-08-21  122340  True      NaN
39        NaN    Male 2016-01-29  122173  True       IT

### 5.4.4 Dealing with null values

In [46]:
# restore our dataset
employees = pd.read_csv("employees.csv", parse_dates=["Start Date"])
employees.head()

C:\Users\lorra\AppData\Local\Temp\ipykernel_40924\2505202037.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  employees = pd.read_csv("employees.csv", parse_dates=["Start Date"])

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

In [47]:
employees.dropna()

    First Name  Gender Start Date    Salary   Mgmt          Team
4        Larry    Male 1998-01-24  101004.0   True            IT
5       Dennis    Male 1987-04-18  115163.0  False         Legal
6         Ruby  Female 1987-08-17   65476.0   True       Product
8       Angela  Female 2005-11-22   95570.0   True   Engineering
9      Frances  Female 2002-08-08  139852.0   True  Business Dev
..         ...     ...        ...       ...    ...           ...
994     George    Male 2013-06-21   98874.0   True     Marketing
996    Phillip    Male 1984-01-31   42392.0  False       Finance
997    Russell    Male 2013-05-20   96914.0  False       Product
998      Larry    Male 2013-04-20   60500.0  False  Business Dev
999     Albert    Male 2012-05-15  129949.0   True         Sales

[761 rows x 6 columns]

In [48]:
employees.tail()

     First Name Gender Start Date    Salary   Mgmt          Team
996     Phillip   Male 1984-01-31   42392.0  False       Finance
997     Russell   Male 2013-05-20   96914.0  False       Product
998       Larry   Male 2013-04-20   60500.0  False  Business Dev
999      Albert   Male 2012-05-15  129949.0   True         Sales
1000        NaN    NaN        NaT       NaN    NaN           NaN

In [49]:
employees.dropna(how='all').tail()

    First Name Gender Start Date    Salary   Mgmt          Team
995      Henry    NaN 2014-11-23  132483.0  False  Distribution
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [50]:
# use subnet parameter to target a column
employees.dropna(subset=["Gender"]).tail()

    First Name Gender Start Date    Salary   Mgmt          Team
994     George   Male 2013-06-21   98874.0   True     Marketing
996    Phillip   Male 1984-01-31   42392.0  False       Finance
997    Russell   Male 2013-05-20   96914.0  False       Product
998      Larry   Male 2013-04-20   60500.0  False  Business Dev
999     Albert   Male 2012-05-15  129949.0   True         Sales

In [51]:
# drop, specifying a list of columns
employees.dropna(subset=["Start Date", "Salary"]).head()

  First Name  Gender Start Date    Salary   Mgmt     Team
1     Thomas    Male 1996-03-31   61933.0   True      NaN
3      Jerry     NaN 2005-03-04  138705.0   True  Finance
4      Larry    Male 1998-01-24  101004.0   True       IT
5     Dennis    Male 1987-04-18  115163.0  False    Legal
6       Ruby  Female 1987-08-17   65476.0   True  Product

In [53]:
# filter employees for rows with at least four present values
employees.dropna(thresh=4).head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

## 5.5 Dealing with duplicates

### 5.5.1 The duplicated method

In [54]:
employees.head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

In [55]:
employees["Team"].duplicated().head()

0    False
1    False
2    False
3     True
4    False
Name: Team, dtype: bool

In [56]:
employees["Team"].duplicated(keep="first").head()

0    False
1    False
2    False
3     True
4    False
Name: Team, dtype: bool

In [58]:
employees["Team"].duplicated(keep="last")

0        True
1        True
2        True
3        True
4        True
        ...
996     False
997     False
998     False
999     False
1000    False
Name: Team, Length: 1001, dtype: bool

In [59]:
(~employees["Team"].duplicated()).head()

0     True
1     True
2     True
3    False
4     True
Name: Team, dtype: bool

In [60]:
first_one_in_team = ~employees["Team"].duplicated()
employees[first_one_in_team]

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

### 5.5.2 The drop_duplicates method

In [61]:
# find the first occurence of each unique value in the Team column
employees.drop_duplicates(subset = ["Team"])

   First Name  Gender Start Date    Salary   Mgmt          Team
0     Douglas    Male 1993-08-06       NaN   True     Marketing
1      Thomas    Male 1996-03-31   61933.0   True           NaN
2       Maria  Female        NaT  130590.0  False       Finance
4       Larry    Male 1998-01-24  101004.0   True            IT
5      Dennis    Male 1987-04-18  115163.0  False         Legal
6        Ruby  Female 1987-08-17   65476.0   True       Product
8      Angela  Female 2005-11-22   95570.0   True   Engineering
9     Frances  Female 2002-08-08  139852.0   True  Business Dev
12    Brandon    Male 1980-12-01  112807.0   True            HR
13       Gary    Male 2008-01-27  109831.0  False         Sales
40    Michael    Male 2008-10-10   99283.0   True  Distribution

In [62]:
employees.drop_duplicates(subset = ["Team"], keep = "last")

     First Name  Gender Start Date    Salary   Mgmt          Team
988       Alice  Female 2004-10-05   47638.0  False            HR
989      Justin     NaN 1991-02-10   38344.0  False         Legal
990       Robin  Female 1987-07-24  100765.0   True            IT
993        Tina  Female 1997-05-15   56450.0   True   Engineering
994      George    Male 2013-06-21   98874.0   True     Marketing
995       Henry     NaN 2014-11-23  132483.0  False  Distribution
996     Phillip    Male 1984-01-31   42392.0  False       Finance
997     Russell    Male 2013-05-20   96914.0  False       Product
998       Larry    Male 2013-04-20   60500.0  False  Business Dev
999      Albert    Male 2012-05-15  129949.0   True         Sales
1000        NaN     NaN        NaT       NaN    NaN           NaN

In [63]:
# filters for rows in employees with a unique value in the First Name column (first name appears only one time)
employees.drop_duplicates(subset = ["First Name"], keep = False)

    First Name  Gender Start Date    Salary   Mgmt          Team
5       Dennis    Male 1987-04-18  115163.0  False         Legal
8       Angela  Female 2005-11-22   95570.0   True   Engineering
33        Jean  Female 1993-12-18  119082.0  False  Business Dev
190      Carol  Female 1996-03-19   57783.0  False       Finance
291      Tammy  Female 1984-11-11  132839.0   True            IT
495     Eugene    Male 1984-05-24   81077.0  False         Sales
688      Brian    Male 2007-04-07   93901.0   True         Legal
832      Keith    Male 2003-02-12  120672.0  False         Legal
887      David    Male 2009-12-05   92242.0  False         Legal

In [64]:
employees[employees["First Name"] == "Dennis"]

  First Name Gender Start Date    Salary   Mgmt   Team
5     Dennis   Male 1987-04-18  115163.0  False  Legal

In [65]:
# first occurence of each employee with a unique combination of "First Name" and "Gender" in the dataset
name_is_douglas = employees["First Name"] == "Douglas"
is_male = employees["Gender"] == "Male"
employees[name_is_douglas & is_male]

    First Name Gender Start Date    Salary   Mgmt         Team
0      Douglas   Male 1993-08-06       NaN   True    Marketing
217    Douglas   Male 1999-09-03   83341.0   True           IT
322    Douglas   Male 2002-01-08   41428.0  False      Product
835    Douglas   Male 2007-08-04  132175.0  False  Engineering

In [66]:
employees.drop_duplicates(subset=["Gender", "Team"]).head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

In [69]:
# find a male and female that share the same name
first_name_and_gender = employees.drop_duplicates(subset=["First Name", "Gender"])
first_name_and_gender.head()

  First Name  Gender Start Date    Salary   Mgmt       Team
0    Douglas    Male 1993-08-06       NaN   True  Marketing
1     Thomas    Male 1996-03-31   61933.0   True        NaN
2      Maria  Female        NaT  130590.0  False    Finance
3      Jerry     NaN 2005-03-04  138705.0   True    Finance
4      Larry    Male 1998-01-24  101004.0   True         IT

In [70]:
# number of employees with first name, gender
len(first_name_and_gender)

301

In [76]:
# find all the employees from first_name_and_gender that 
mask = first_name_and_gender["First Name"].duplicated(keep=False)
mask

0       True
1       True
2       True
3       True
4      False
       ...
939     True
950     True
961     True
985     True
995     True
Name: First Name, Length: 301, dtype: bool

In [77]:
first_name_and_gender[mask]

    First Name  Gender Start Date    Salary   Mgmt          Team
0      Douglas    Male 1993-08-06       NaN   True     Marketing
1       Thomas    Male 1996-03-31   61933.0   True           NaN
2        Maria  Female        NaT  130590.0  False       Finance
3        Jerry     NaN 2005-03-04  138705.0   True       Finance
7          NaN  Female 2015-07-20   45906.0    NaN       Finance
..         ...     ...        ...       ...    ...           ...
939      Ralph     NaN 1995-07-28   70635.0  False            IT
950      Paula  Female 1983-05-21   58423.0  False  Business Dev
961    Antonio     NaN 1989-06-18  103050.0  False         Legal
985    Stephen     NaN 1983-07-10   85668.0  False         Legal
995      Henry     NaN 2014-11-23  132483.0  False  Distribution

[199 rows x 6 columns]

In [79]:
first_name_and_gender[first_name_and_gender["First Name"] == "Douglas"]

    First Name Gender Start Date    Salary  Mgmt       Team
0      Douglas   Male 1993-08-06       NaN  True  Marketing
667    Douglas    NaN 2009-02-04  104496.0  True  Marketing

In [80]:
first_name_and_gender[first_name_and_gender["First Name"] == "Thomas"]

    First Name Gender Start Date   Salary   Mgmt   Team
1       Thomas   Male 1996-03-31  61933.0   True    NaN
350     Thomas    NaN 1995-08-31  41549.0  False  Sales