In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'category' : ['A', 'A', 'B', 'B'],
    'sales' : [10, 20, 5, 15],
    'quantity' : [1, 2, 1, 3]
})
df

  category  sales  quantity
0        A     10         1
1        A     20         2
2        B      5         1
3        B     15         3

In [3]:
grouped = df.groupby('category').agg({
    'sales': ['sum', 'mean'],
    'quantity': ['min', 'max']
})
grouped

         sales       quantity
           sum  mean      min max
category
A           30  15.0        1   2
B           20  10.0        1   3

In [4]:
for col in grouped.columns:
    print(col)

('sales', 'sum')
('sales', 'mean')
('quantity', 'min')
('quantity', 'max')

In [5]:
grouped.columns = ['_'.join(col) for col in grouped.columns] 
grouped.columns

Index(['sales_sum', 'sales_mean', 'quantity_min', 'quantity_max'], dtype='object')

In [6]:
grouped

          sales_sum  sales_mean  quantity_min  quantity_max
category
A                30        15.0             1             2
B                20        10.0             1             3