In [1]:
import numpy as np
import pandas as pd

In [9]:
# Create an untidy data set
dict = { "Sara" : ["27", 1.77, "Belgium"],
         "Lis": ["30", 5.58, "USA"],
         "Hadrien" : ["", 1.80, "FR"],
         "Lis": ["30", 5.58, "USA"]}

In [11]:
df = pd.DataFrame(dict, index = ["Age", "Size", "Country"])
df

            Sara   Lis Hadrien
Age           27    30
Size        1.77  5.58     1.8
Country  Belgium   USA      FR

In [14]:
list(df.columns)

['Sara', 'Lis', 'Hadrien']

In [16]:
list(df.index)

['Age', 'Size', 'Country']

In [18]:
df

            Sara   Lis Hadrien
Age           27    30
Size        1.77  5.58     1.8
Country  Belgium   USA      FR

In [19]:
df.T

        Age  Size  Country
Sara     27  1.77  Belgium
Lis      30  5.58      USA
Hadrien       1.8       FR

In [20]:
df = df.T
df

        Age  Size  Country
Sara     27  1.77  Belgium
Lis      30  5.58      USA
Hadrien       1.8       FR

In [21]:
df.reset_index()

     index Age  Size  Country
0     Sara  27  1.77  Belgium
1      Lis  30  5.58      USA
2  Hadrien       1.8       FR