In [1]:
import numpy as np
import pandas as pd

In [7]:
countries = ["Italy", "Italy", "Spain", "Spain"]
years = [2017, 2018, 2017, 2018]
row_index = pd.MultiIndex.from_arrays([countries, years], names=["country", "year"])
row_index

MultiIndex([('Italy', 2017),
            ('Italy', 2018),
            ('Spain', 2017),
            ('Spain', 2018)],
           names=['country', 'year'])

In [11]:
# define the column index 
col_index = pd.MultiIndex.from_product(
    [["office supply", "Technology"], ["online", "onsite"]],
    names=[None, "shop"]
)
col_index

MultiIndex([('office supply', 'online'),
            ('office supply', 'onsite'),
            (   'Technology', 'online'),
            (   'Technology', 'onsite')],
           names=[None, 'shop'])

In [12]:
data = np.array([[310, 123, 510, 340],[110, 100, 610, 120], [229, 200, 300, 240], [120, 220, 190, 210]])
data

array([[310, 123, 510, 340],
       [110, 100, 610, 120],
       [229, 200, 300, 240],
       [120, 220, 190, 210]])

In [15]:
sales = pd.DataFrame(data, index=row_index, columns=col_index)
sales

             office supply        Technology
shop                online onsite     online onsite
country year
Italy   2017           310    123        510    340
        2018           110    100        610    120
Spain   2017           229    200        300    240
        2018           120    220        190    210

In [16]:
sales.columns.names

FrozenList([None, 'shop'])

In [18]:
sales.stack(future_stack=True)

                     office supply  Technology
country year shop
Italy   2017 online            310         510
             onsite            123         340
        2018 online            110         610
             onsite            100         120
Spain   2017 online            229         300
             onsite            200         240
        2018 online            120         190
             onsite            220         210

In [19]:
sales.stack(future_stack=True).sum(axis=1)

country  year  shop
Italy    2017  online    820
               onsite    463
         2018  online    720
               onsite    220
Spain    2017  online    529
               onsite    440
         2018  online    310
               onsite    430
dtype: int64

In [20]:
# sum by country and year
sales.index.names

FrozenList(['country', 'year'])

In [25]:
sales.stack(future_stack=True)['shop']

KeyError: 'shop'