# 4. The DataFrame Object

In [1]:
import pandas as pd
import numpy as np

### 4.1.1 Creating a DataFrame from a dictionary

In [2]:
city_data = {
            "City": ["New York City", "Paris", "Barcelona", "Rome"],
            "Country": ["United States", "France", "Spain", "Italy"],
            "Population": [8600000, 2141000, 5515000, 2873000]
        }
cities = pd.DataFrame(city_data)
cities

            City        Country  Population
0  New York City  United States     8600000
1          Paris         France     2141000
2      Barcelona          Spain     5515000
3           Rome          Italy     2873000

In [3]:
# What if we wanted to swap the column headers with the index labels
cities.transpose()

                        0        1          2        3
City        New York City    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

In [4]:
cities.loc[0,:]

City          New York City
Country       United States
Population          8600000
Name: 0, dtype: object

In [5]:
type(cities.transpose())

pandas.core.frame.DataFrame

In [6]:
cities.transpose().loc['City', :]

0    New York City
1            Paris
2        Barcelona
3             Rome
Name: City, dtype: object

In [7]:
# This is the same as using transpose()
cities.T

                        0        1          2        3
City        New York City    Paris  Barcelona     Rome
Country     United States   France      Spain    Italy
Population        8600000  2141000    5515000  2873000

### 4.1.2 Creating a DataFrame from a NumPy ndarray

In [8]:
# create a 3 x 5 ndarray of integers between 1 and 101 (exclusive)
random_data = np.random.randint(1, 101, [3,5])
random_data

array([[89,  8, 67, 86, 97],
       [35, 56, 21,  1, 95],
       [55, 78, 11, 87, 99]], dtype=int32)

In [9]:
pd.DataFrame(data=random_data)

    0   1   2   3   4
0  89   8  67  86  97
1  35  56  21   1  95
2  55  78  11  87  99

In [10]:
row_labels = ["Morning", "Afternoon", "Evening"]
temperatures = pd.DataFrame(data = random_data, index = row_labels)
temperatures

            0   1   2   3   4
Morning    89   8  67  86  97
Afternoon  35  56  21   1  95
Evening    55  78  11  87  99

In [11]:
column_labels = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
pd.DataFrame(data= random_data, index=row_labels, columns = column_labels)

           Monday  Tuesday  Wednesday  Thursday  Friday
Morning        89        8         67        86      97
Afternoon      35       56         21         1      95
Evening        55       78         11        87      99

In [12]:
pd.read_csv("nba.csv")

               Name                 Team Position  Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG   9/26/96   1445697
1    Christian Wood      Detroit Pistons       PF   9/27/95   1645357
2     PJ Washington    Charlotte Hornets       PF   8/23/98   3831840
3      Derrick Rose      Detroit Pistons       PG   10/4/88   7317074
4     Marial Shayok   Philadelphia 76ers        G   7/26/95     79568
..              ...                  ...      ...       ...       ...
445   Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446     Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447     Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449     Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

[450 rows x 5 columns]

In [13]:
nba = pd.read_csv("nba.csv", parse_dates = ["Birthday"], date_format ="%m/%d/%y")

In [14]:
nba.dtypes

Name                object
Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [15]:
nba.dtypes.value_counts()

object            3
datetime64[ns]    1
int64             1
Name: count, dtype: int64

In [16]:
nba.index

RangeIndex(start=0, stop=450, step=1)

In [17]:
nba.columns

Index(['Name', 'Team', 'Position', 'Birthday', 'Salary'], dtype='object')

In [18]:
nba.ndim

2

In [19]:
nba.shape

(450, 5)

In [20]:
nba.size

2250

In [21]:
nba.count()

Name        450
Team        450
Position    450
Birthday    450
Salary      450
dtype: int64

In [22]:
nba.count().sum()

np.int64(2250)

In [23]:
# an example when there are missing values
data = {
    "A": [1, np.nan],
    "B": [2, 3]
}
df = pd.DataFrame(data)
df

     A  B
0  1.0  2
1  NaN  3

In [24]:
df.size

4

In [25]:
df.count().sum()

np.int64(3)

In [26]:
nba.head(2)

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [27]:
nba.tail(3)

              Name                 Team Position   Birthday    Salary
447    Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448  Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449    Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

In [28]:
nba.sample(3)

               Name                   Team Position   Birthday    Salary
156     Luka Doncic       Dallas Mavericks       PG 1999-02-28   7683360
244        Miye Oni              Utah Jazz       SG 1997-08-04    898310
282  Andre Roberson  Oklahoma City Thunder       SF 1991-12-04  10740740

In [29]:
# Suppose you want to find out how many teams, salaries, and positions exist
nba.nunique()

Name        450
Team         30
Position      9
Birthday    430
Salary      269
dtype: int64

In [30]:
nba.max()

Name             Zylan Cheatham
Team         Washington Wizards
Position                     SG
Birthday    2000-12-23 00:00:00
Salary                 40231758
dtype: object

In [31]:
nba.min()

Name               Aaron Gordon
Team              Atlanta Hawks
Position                      C
Birthday    1977-01-26 00:00:00
Salary                    79568
dtype: object

In [32]:
# What if we want to identify the four highest-paid players?
nba.nlargest(n=4, columns="Salary")

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
251          John Wall     Washington Wizards       PG 1990-09-06  38199000

In [33]:
nba.sort_values(by="Salary", ascending=False).head(4)

                  Name                   Team Position   Birthday    Salary
205      Stephen Curry  Golden State Warriors       PG 1988-03-14  40231758
38          Chris Paul  Oklahoma City Thunder       PG 1985-05-06  38506482
219  Russell Westbrook        Houston Rockets       PG 1988-11-12  38506482
264       James Harden        Houston Rockets       PG 1989-08-26  38199000

In [34]:
# Find the three oldest players in the league
nba.nsmallest(n=3, columns=["Birthday"])

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

In [35]:
nba.sort_values(by="Birthday", ascending=True).head(3)

              Name             Team Position   Birthday   Salary
98    Vince Carter    Atlanta Hawks       PF 1977-01-26  2564753
196  Udonis Haslem       Miami Heat        C 1980-06-09  2564753
262    Kyle Korver  Milwaukee Bucks       PF 1981-03-17  6004753

In [36]:
nba['Salary'].sum()

np.int64(3444112694)

In [37]:
nba.mean(numeric_only=True)

Salary    7.653584e+06
dtype: float64

In [38]:
nba.median(numeric_only=True)

Salary    3303074.5
dtype: float64

In [39]:
nba.std(numeric_only=True)

Salary    9.288810e+06
dtype: float64

## 4.3 Sorting a DataFrame

### 4.3.1 Sorting by a single column

In [40]:
nba.sort_values("Name")

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [41]:
nba.sort_values("Name", ascending=False).head()

                Name                  Team Position   Birthday    Salary
248   Zylan Cheatham  New Orleans Pelicans       SF 1995-11-17     79568
137  Zion Williamson  New Orleans Pelicans        F 2000-07-06   9757440
312     Zhaire Smith    Philadelphia 76ers       SG 1999-06-04   3058800
302     Zach Norvell    Los Angeles Lakers       SG 1997-12-09     79568
159      Zach LaVine         Chicago Bulls       PG 1995-03-10  19500000

### 4.3.2 Sorting by multiple columns

In [42]:
nba.sort_values(by=["Team", "Name"]).head()

                Name           Team Position   Birthday    Salary
359         Alex Len  Atlanta Hawks        C 1993-06-16   4160000
167     Allen Crabbe  Atlanta Hawks       SG 1992-04-09  18500000
276  Brandon Goodwin  Atlanta Hawks       PG 1995-10-02     79568
438   Bruno Fernando  Atlanta Hawks        C 1998-08-15   1400000
194      Cam Reddish  Atlanta Hawks       SF 1999-09-01   4245720

In [44]:
nba.sort_values(by=['Team', 'Salary'], ascending=[True, False])

                  Name                Team Position   Birthday    Salary
111   Chandler Parsons       Atlanta Hawks       SF 1988-10-25  25102512
28         Evan Turner       Atlanta Hawks       PG 1988-10-27  18606556
167       Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
213    De'Andre Hunter       Atlanta Hawks       SF 1997-12-02   7068360
339      Jabari Parker       Atlanta Hawks       PF 1995-03-15   6500000
..                 ...                 ...      ...        ...       ...
80         Isaac Bonga  Washington Wizards       PG 1999-11-08   1416852
399  Admiral Schofield  Washington Wizards       SF 1997-03-30   1000000
273    Justin Robinson  Washington Wizards       PG 1997-10-12    898310
283   Garrison Mathews  Washington Wizards       SG 1996-10-24     79568
353      Chris Chiozza  Washington Wizards       PG 1995-11-21     79568

[450 rows x 5 columns]

In [45]:
nba = nba.sort_values(by=['Team', 'Salary'], ascending=[True, False])
nba.head()

                 Name           Team Position   Birthday    Salary
111  Chandler Parsons  Atlanta Hawks       SF 1988-10-25  25102512
28        Evan Turner  Atlanta Hawks       PG 1988-10-27  18606556
167      Allen Crabbe  Atlanta Hawks       SG 1992-04-09  18500000
213   De'Andre Hunter  Atlanta Hawks       SF 1997-12-02   7068360
339     Jabari Parker  Atlanta Hawks       PF 1995-03-15   6500000

## 4.4 Sorting by index

In [46]:
# The dataframe now has a different order (check the index)
nba.head()

                 Name           Team Position   Birthday    Salary
111  Chandler Parsons  Atlanta Hawks       SF 1988-10-25  25102512
28        Evan Turner  Atlanta Hawks       PG 1988-10-27  18606556
167      Allen Crabbe  Atlanta Hawks       SG 1992-04-09  18500000
213   De'Andre Hunter  Atlanta Hawks       SF 1997-12-02   7068360
339     Jabari Parker  Atlanta Hawks       PF 1995-03-15   6500000

### 4.4.1 Sorting by row index

In [47]:
nba.sort_index().head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

In [48]:
# reverse the sort order
nba.sort_index(ascending=False).head()

              Name                 Team Position   Birthday    Salary
449    Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000
448  Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
447    Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
446    Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
445  Austin Rivers      Houston Rockets       PG 1992-08-01   2174310

In [49]:
nba = nba.sort_index()
nba.head()

             Name                Team Position   Birthday   Salary
0    Shake Milton  Philadelphia 76ers       SG 1996-09-26  1445697
1  Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
2   PJ Washington   Charlotte Hornets       PF 1998-08-23  3831840
3    Derrick Rose     Detroit Pistons       PG 1988-10-04  7317074
4   Marial Shayok  Philadelphia 76ers        G 1995-07-26    79568

### 4.4.2 Sorting by column index

In [50]:
# sort the columns in ascending order
nba.sort_index(axis="columns").head()

    Birthday            Name Position   Salary                Team
0 1996-09-26    Shake Milton       SG  1445697  Philadelphia 76ers
1 1995-09-27  Christian Wood       PF  1645357     Detroit Pistons
2 1998-08-23   PJ Washington       PF  3831840   Charlotte Hornets
3 1988-10-04    Derrick Rose       PG  7317074     Detroit Pistons
4 1995-07-26   Marial Shayok        G    79568  Philadelphia 76ers

## 4.5 Setting a new index

In [52]:
nba.set_index(keys="Name").head()

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840
Derrick Rose       Detroit Pistons       PG 1988-10-04  7317074
Marial Shayok   Philadelphia 76ers        G 1995-07-26    79568

In [53]:
nba = nba.set_index(keys="Name")

In [54]:
nba.head()

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840
Derrick Rose       Detroit Pistons       PG 1988-10-04  7317074
Marial Shayok   Philadelphia 76ers        G 1995-07-26    79568

In [55]:
# We could set the index to a specific column when we read in the file
nba = pd.read_csv("nba.csv", parse_dates = ["Birthday"], date_format ="%m/%d/%y", index_col="Name")

In [56]:
nba.head()

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357
PJ Washington    Charlotte Hornets       PF 1998-08-23  3831840
Derrick Rose       Detroit Pistons       PG 1988-10-04  7317074
Marial Shayok   Philadelphia 76ers        G 1995-07-26    79568

## 4.6 Selecting columns and rows from a Dataframe

### 4.6.1 Selecting a single column from a DataFrame

In [57]:
nba.Salary

Name
Shake Milton       1445697
Christian Wood     1645357
PJ Washington      3831840
Derrick Rose       7317074
Marial Shayok        79568
                    ...
Austin Rivers      2174310
Harry Giles        2578800
Robin Lopez        4767000
Collin Sexton      4764960
Ricky Rubio       16200000
Name: Salary, Length: 450, dtype: int64

In [58]:
nba["Position"]

Name
Shake Milton      SG
Christian Wood    PF
PJ Washington     PF
Derrick Rose      PG
Marial Shayok      G
                  ..
Austin Rivers     PG
Harry Giles       PF
Robin Lopez        C
Collin Sexton     PG
Ricky Rubio       PG
Name: Position, Length: 450, dtype: object

### 4.6.2 Selecting multiple columns from a DataFrame

In [59]:
nba[["Salary", "Birthday"]]

                  Salary   Birthday
Name
Shake Milton     1445697 1996-09-26
Christian Wood   1645357 1995-09-27
PJ Washington    3831840 1998-08-23
Derrick Rose     7317074 1988-10-04
Marial Shayok      79568 1995-07-26
...                  ...        ...
Austin Rivers    2174310 1992-08-01
Harry Giles      2578800 1998-04-22
Robin Lopez      4767000 1988-04-01
Collin Sexton    4764960 1999-01-04
Ricky Rubio     16200000 1990-10-21

[450 rows x 2 columns]

In [60]:
nba.dtypes

Team                object
Position            object
Birthday    datetime64[ns]
Salary               int64
dtype: object

In [61]:
nba.select_dtypes(include="object")

                               Team Position
Name
Shake Milton     Philadelphia 76ers       SG
Christian Wood      Detroit Pistons       PF
PJ Washington     Charlotte Hornets       PF
Derrick Rose        Detroit Pistons       PG
Marial Shayok    Philadelphia 76ers        G
...                             ...      ...
Austin Rivers       Houston Rockets       PG
Harry Giles        Sacramento Kings       PF
Robin Lopez         Milwaukee Bucks        C
Collin Sexton   Cleveland Cavaliers       PG
Ricky Rubio            Phoenix Suns       PG

[450 rows x 2 columns]

In [62]:
# select all columns except string and integer columns
nba.select_dtypes(exclude=["object", "int"])

                 Birthday
Name
Shake Milton   1996-09-26
Christian Wood 1995-09-27
PJ Washington  1998-08-23
Derrick Rose   1988-10-04
Marial Shayok  1995-07-26
...                   ...
Austin Rivers  1992-08-01
Harry Giles    1998-04-22
Robin Lopez    1988-04-01
Collin Sexton  1999-01-04
Ricky Rubio    1990-10-21

[450 rows x 1 columns]

## 4.7 Selecting rows from a DataFrame

### 4.7.1 Extracting rows by index label

In [63]:
nba.loc["LeBron James"]

Team         Los Angeles Lakers
Position                     PF
Birthday    1984-12-30 00:00:00
Salary                 37436858
Name: LeBron James, dtype: object

In [64]:
type(nba.loc["LeBron James"])

pandas.core.series.Series

In [65]:
nba.loc[["Kawhi Leonard", "Paul George"]]

                               Team Position   Birthday    Salary
Name
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556

In [66]:
nba.loc[["Paul George", "Kawhi Leonard"]]

                               Team Position   Birthday    Salary
Name
Paul George    Los Angeles Clippers       SF 1990-05-02  33005556
Kawhi Leonard  Los Angeles Clippers       SF 1991-06-29  32742000

In [67]:
nba.sort_index().loc["Otto Porter" : "Patrick Beverley"]

                                  Team Position   Birthday    Salary
Name
Otto Porter              Chicago Bulls       SF 1993-06-03  27250576
PJ Dozier               Denver Nuggets       PG 1996-10-25     79568
PJ Washington        Charlotte Hornets       PF 1998-08-23   3831840
Pascal Siakam          Toronto Raptors       PF 1994-04-02   2351838
Pat Connaughton        Milwaukee Bucks       SG 1993-01-06   1723050
Patrick Beverley  Los Angeles Clippers       PG 1988-07-12  12345680

In [68]:
nba.sort_index().loc["Zach Collins":]

                                   Team Position   Birthday    Salary
Name
Zach Collins     Portland Trail Blazers        C 1997-11-19   4240200
Zach LaVine               Chicago Bulls       PG 1995-03-10  19500000
Zach Norvell         Los Angeles Lakers       SG 1997-12-09     79568
Zhaire Smith         Philadelphia 76ers       SG 1999-06-04   3058800
Zion Williamson    New Orleans Pelicans        F 2000-07-06   9757440
Zylan Cheatham     New Orleans Pelicans       SF 1995-11-17     79568

In [69]:
nba.sort_index().loc[:"Al Horford"]

                                    Team Position   Birthday    Salary
Name
Aaron Gordon               Orlando Magic       PF 1995-09-16  19863636
Aaron Holiday             Indiana Pacers       PG 1996-09-30   2239200
Abdel Nader        Oklahoma City Thunder       SF 1993-09-25   1618520
Adam Mokoka                Chicago Bulls        G 1998-07-18     79568
Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
Al Horford            Philadelphia 76ers        C 1986-06-03  28000000

### 4.7.2 Extracting rows by index position

In [70]:
nba.iloc[300]

Team             Denver Nuggets
Position                     PF
Birthday    1999-04-03 00:00:00
Salary                  1416852
Name: Jarred Vanderbilt, dtype: object

In [71]:
nba.iloc[[300]]

                             Team Position   Birthday   Salary
Name
Jarred Vanderbilt  Denver Nuggets       PF 1999-04-03  1416852

In [72]:
nba.iloc[[100, 200, 300, 400]]

                                Team Position   Birthday   Salary
Name
Brian Bowen           Indiana Pacers       SG 1998-10-02    79568
Marco Belinelli    San Antonio Spurs       SF 1986-03-25  5846154
Jarred Vanderbilt     Denver Nuggets       PF 1999-04-03  1416852
Louis King           Detroit Pistons        F 1999-04-06    79568

In [73]:
len(nba)

450

In [74]:
nba.iloc[400:404]

                                    Team Position   Birthday    Salary
Name
Louis King               Detroit Pistons        F 1999-04-06     79568
Kostas Antetokounmpo  Los Angeles Lakers       PF 1997-11-20     79568
Rodions Kurucs             Brooklyn Nets       PF 1998-02-05   1699236
Spencer Dinwiddie          Brooklyn Nets       PG 1993-04-06  10605600

In [75]:
nba.iloc[:2]

                              Team Position   Birthday   Salary
Name
Shake Milton    Philadelphia 76ers       SG 1996-09-26  1445697
Christian Wood     Detroit Pistons       PF 1995-09-27  1645357

In [76]:
nba.iloc[447:]

                              Team Position   Birthday    Salary
Name
Robin Lopez        Milwaukee Bucks        C 1988-04-01   4767000
Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
Ricky Rubio           Phoenix Suns       PG 1990-10-21  16200000

In [77]:
nba.iloc[-10:-6]

                                    Team Position   Birthday   Salary
Name
Jared Dudley          Los Angeles Lakers       PF 1985-07-10  2564753
Max Strus                  Chicago Bulls       SG 1996-03-28    79568
Kevon Looney       Golden State Warriors        C 1996-02-06  4464286
Willy Hernangomez      Charlotte Hornets        C 1994-05-27  1557250

In [78]:
nba.iloc[0:10:2]

                             Team Position   Birthday    Salary
Name
Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
PJ Washington   Charlotte Hornets       PF 1998-08-23   3831840
Marial Shayok  Philadelphia 76ers        G 1995-07-26     79568
Kendrick Nunn          Miami Heat       SG 1995-08-03   1416852
Brook Lopez       Milwaukee Bucks        C 1988-04-01  12093024

### 4.7.3 Extracting values from specific columns