# 🧭 The Complete Guide to DataFrame Index Operations in pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
# prepare a simple file
df = pd.DataFrame({
    "city": ["Paris", "Paris", "London", "London", "Berlin"],
    "year": [2020, 2021, 2020, 2021, 2020],
    "population": [2.1, 2.2, 8.9, 9.0, 3.6]
})

df

     city  year  population
0   Paris  2020         2.1
1   Paris  2021         2.2
2  London  2020         8.9
3  London  2021         9.0
4  Berlin  2020         3.6

### 🟦 Option 1: A tidy DataFrame with a normal RangeIndex

Perfect for practicing **set_index**, **reset_index**, **reindex**, **sort_index**, and **filtering**.
```
import pandas as pd

df = pd.DataFrame({
    "city": ["Paris", "Paris", "London", "London", "Berlin"],
    "year": [2020, 2021, 2020, 2021, 2020],
    "population": [2.1, 2.2, 8.9, 9.0, 3.6]
})

df
```

In [3]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
df.index.name

In [5]:
df.index.dtype

dtype('int64')

In [6]:
df.index.values

array([0, 1, 2, 3, 4])

In [7]:
df.index.to_list()

[0, 1, 2, 3, 4]

In [8]:
# make a deep copy 
df_copy = df.copy()

In [9]:
df_copy

     city  year  population
0   Paris  2020         2.1
1   Paris  2021         2.2
2  London  2020         8.9
3  London  2021         9.0
4  Berlin  2020         3.6

In [17]:
df2 = df_copy.reset_index()
df2

   index    city  year  population
0      0   Paris  2020         2.1
1      1   Paris  2021         2.2
2      2  London  2020         8.9
3      3  London  2021         9.0
4      4  Berlin  2020         3.6

In [18]:
df2.index

RangeIndex(start=0, stop=5, step=1)

In [19]:
df_copy = df.copy()
df2 = df_copy.reset_index(drop=True)
df2

     city  year  population
0   Paris  2020         2.1
1   Paris  2021         2.2
2  London  2020         8.9
3  London  2021         9.0
4  Berlin  2020         3.6

In [20]:
df2.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
df_copy = df.copy()
df_copy

     city  year  population
0   Paris  2020         2.1
1   Paris  2021         2.2
2  London  2020         8.9
3  London  2021         9.0
4  Berlin  2020         3.6

In [16]:
df2 = df_copy.set_index("population")
df2

              city  year
population
2.1          Paris  2020
2.2          Paris  2021
8.9         London  2020
9.0         London  2021
3.6         Berlin  2020

In [22]:
df_copy = df.copy()
df2 = df_copy.sort_index(ascending=False)
df2

     city  year  population
4  Berlin  2020         3.6
3  London  2021         9.0
2  London  2020         8.9
1   Paris  2021         2.2
0   Paris  2020         2.1

In [24]:
df_copy = df.copy()
df2 = df_copy.rename(index={0:'p1', 1:'p2', 2:'p3', 3:'p4', 4:'p5'})
df2

      city  year  population
p1   Paris  2020         2.1
p2   Paris  2021         2.2
p3  London  2020         8.9
p4  London  2021         9.0
p5  Berlin  2020         3.6

In [30]:
# more Pythonic way of doing the above
df_copy = df.copy()
df2 = df_copy.rename(index={x: f"p{x+1}" for x in df_copy.index.to_list()})
df2

      city  year  population
p1   Paris  2020         2.1
p2   Paris  2021         2.2
p3  London  2020         8.9
p4  London  2021         9.0
p5  Berlin  2020         3.6

In [37]:
df2.loc['p1']

city          Paris
year           2020
population      2.1
Name: p1, dtype: object

In [38]:
df2.loc[['p2', 'p4']]

      city  year  population
p2   Paris  2021         2.2
p4  London  2021         9.0

In [39]:
df2.iloc[0]

city          Paris
year           2020
population      2.1
Name: p1, dtype: object

In [40]:
df2.iloc[[1, 3]]

      city  year  population
p2   Paris  2021         2.2
p4  London  2021         9.0

In [43]:
df3 = df2.reset_index()
df3

  index    city  year  population
0    p1   Paris  2020         2.1
1    p2   Paris  2021         2.2
2    p3  London  2020         8.9
3    p4  London  2021         9.0
4    p5  Berlin  2020         3.6

In [47]:
df_paris = df3[df3['city'] == 'London'].reset_index()
df_paris

   level_0 index    city  year  population
0        2    p3  London  2020         8.9
1        3    p4  London  2021         9.0

In [49]:
df2

      city  year  population
p1   Paris  2020         2.1
p2   Paris  2021         2.2
p3  London  2020         8.9
p4  London  2021         9.0
p5  Berlin  2020         3.6

In [50]:
df4 = df2.drop(index='p3')
df4

      city  year  population
p1   Paris  2020         2.1
p2   Paris  2021         2.2
p4  London  2021         9.0
p5  Berlin  2020         3.6

In [52]:
df5 = df2[df2.index > 'p3']
df5

      city  year  population
p4  London  2021         9.0
p5  Berlin  2020         3.6

In [53]:
df2

      city  year  population
p1   Paris  2020         2.1
p2   Paris  2021         2.2
p3  London  2020         8.9
p4  London  2021         9.0
p5  Berlin  2020         3.6

In [55]:
df2.index = pd.RangeIndex(start=10, stop=10+len(df2))
df2

      city  year  population
10   Paris  2020         2.1
11   Paris  2021         2.2
12  London  2020         8.9
13  London  2021         9.0
14  Berlin  2020         3.6