# Cleaning Data in Python

## Chapter 1: Common Problems

### Data type constraints

In [1]:
import pandas as pd
import numpy as np

In [2]:
ride_sharing_new = pd.read_csv("ride_sharing_new.csv")
ride_sharing_new.head()

,Unnamed: 0,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender
0,0,12 minutes,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male
1,1,24 minutes,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male
2,2,8 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male
3,3,4 minutes,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male
4,4,11 minutes,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male

In [3]:
ride_sharing_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       25760 non-null  int64
 1   duration         25760 non-null  object
 2   station_A_id     25760 non-null  int64
 3   station_A_name   25760 non-null  object
 4   station_B_id     25760 non-null  int64
 5   station_B_name   25760 non-null  object
 6   bike_id          25760 non-null  int64
 7   user_type        25760 non-null  int64
 8   user_birth_year  25760 non-null  int64
 9   user_gender      25760 non-null  object
dtypes: int64(6), object(4)
memory usage: 2.0+ MB

In [4]:
ride_sharing_new['user_type'].describe()

count    25760.000000
mean         2.008385
std          0.704541
min          1.000000
25%          2.000000
50%          2.000000
75%          3.000000
max          3.000000
Name: user_type, dtype: float64

In [5]:
ride_sharing_new['user_type'].unique()

array([2, 3, 1])

In [6]:
# convert user_type into categorical
ride_sharing_new['user_type_cat'] = ride_sharing_new['user_type'].astype('category')

In [7]:
# write an assert statement confirming the change
assert ride_sharing_new['user_type_cat'].dtype == 'category'

In [8]:
# print summary statistics
ride_sharing_new['user_type_cat'].describe()

count     25760
unique        3
top           2
freq      12972
Name: user_type_cat, dtype: int64

In [9]:
# examining the duration column
ride_sharing_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       25760 non-null  int64
 1   duration         25760 non-null  object
 2   station_A_id     25760 non-null  int64
 3   station_A_name   25760 non-null  object
 4   station_B_id     25760 non-null  int64
 5   station_B_name   25760 non-null  object
 6   bike_id          25760 non-null  int64
 7   user_type        25760 non-null  int64
 8   user_birth_year  25760 non-null  int64
 9   user_gender      25760 non-null  object
 10  user_type_cat    25760 non-null  category
dtypes: category(1), int64(6), object(4)
memory usage: 2.0+ MB

In [10]:
ride_sharing_new['duration'].head()

0    12 minutes
1    24 minutes
2     8 minutes
3     4 minutes
4    11 minutes
Name: duration, dtype: object

- Use the .strip() method to strip duration of "minutes" and store it in the duration_trim column.
- Convert duration_trim to int and store it in the duration_time column.
- Write an assert statement that checks if duration_time's data type is now an int.
- Print the average ride duration.

In [11]:
# Strip duration of minutes
ride_sharing_new['duration_trim'] = ride_sharing_new['duration'].str.strip("minutes")

# Convert duration to integer
ride_sharing_new['duration_time'] = ride_sharing_new['duration_trim'].astype('int')

# Write an assert statement making sure of conversion
assert ride_sharing_new['duration_time'].dtype == 'int'

# Print formed columns and calculate average ride duration 
print(ride_sharing_new[['duration','duration_trim','duration_time']])
print(ride_sharing_new['duration_time'].mean())

         duration duration_trim  duration_time
0      12 minutes           12              12
1      24 minutes           24              24
2       8 minutes            8               8
3       4 minutes            4               4
4      11 minutes           11              11
...           ...           ...            ...
25755  11 minutes           11              11
25756  10 minutes           10              10
25757  14 minutes           14              14
25758  14 minutes           14              14
25759  29 minutes           29              29

[25760 rows x 3 columns]
11.389052795031056

### Data range constraints

In [12]:
import datetime as dt

In [13]:
today_date = dt.date.today()
today_date

datetime.date(2025, 11, 14)

#### Exercise: Tire size constraints

In this lesson, you're going to build on top of the work you've been doing with the ride_sharing DataFrame. You'll be working with the tire_sizes column which contains data on each bike's tire size.
Bicycle tire sizes could be either 26″, 27″ or 29″ and are here correctly stored as a categorical value. In an effort to cut maintenance costs, the ride sharing provider decided to set the maximum tire size to be 27″.
In this exercise, you will make sure the tire_sizes column has the correct range by first converting it to an integer, then setting and testing the new upper limit of 27″ for tire sizes.

#### Instructions
- Convert the tire_sizes column from category to 'int'.
- Use .loc[] to set all values of tire_sizes above 27 to 27.
- Reconvert back tire_sizes to 'category' from int.
- Print the description of the tire_sizes.

In [14]:
ride_sharing_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       25760 non-null  int64
 1   duration         25760 non-null  object
 2   station_A_id     25760 non-null  int64
 3   station_A_name   25760 non-null  object
 4   station_B_id     25760 non-null  int64
 5   station_B_name   25760 non-null  object
 6   bike_id          25760 non-null  int64
 7   user_type        25760 non-null  int64
 8   user_birth_year  25760 non-null  int64
 9   user_gender      25760 non-null  object
 10  user_type_cat    25760 non-null  category
 11  duration_trim    25760 non-null  object
 12  duration_time    25760 non-null  int64
dtypes: category(1), int64(7), object(5)
memory usage: 2.4+ MB

<span style="color:red">There is no column named *tire_sizes* in the dataset provided in the course</span>

In [15]:
ride_sharing_new['Unnamed: 0'].unique()

array([    0,     1,     2, ..., 25757, 25758, 25759], shape=(25760,))

In [16]:
ride_sharing_new.rename(columns={ 'Unnamed: 0': 'ride_id'}, inplace=True)

In [17]:
ride_sharing_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ride_id          25760 non-null  int64
 1   duration         25760 non-null  object
 2   station_A_id     25760 non-null  int64
 3   station_A_name   25760 non-null  object
 4   station_B_id     25760 non-null  int64
 5   station_B_name   25760 non-null  object
 6   bike_id          25760 non-null  int64
 7   user_type        25760 non-null  int64
 8   user_birth_year  25760 non-null  int64
 9   user_gender      25760 non-null  object
 10  user_type_cat    25760 non-null  category
 11  duration_trim    25760 non-null  object
 12  duration_time    25760 non-null  int64
dtypes: category(1), int64(7), object(5)
memory usage: 2.4+ MB

- Find duplicated rows of ride_id in the ride_sharing DataFrame while setting keep to False.
- Subset ride_sharing on duplicates and sort by ride_id and assign the results to duplicated_rides.
- Print the ride_id, duration and user_birth_year columns of duplicated_rides in that order.

In [18]:
# Find duplicates
duplicates = ride_sharing_new.duplicated('ride_id', keep=False)

In [19]:
# Sort your duplicated rides
duplicated_rides = ride_sharing_new[duplicates].sort_values('ride_id')

In [20]:
# print relevant columns of duplicaated_rides
duplicated_rides[['ride_id', 'duration', 'user_birth_year']]

Empty DataFrame
Columns: [ride_id, duration, user_birth_year]
Index: []

In [21]:
# An example from co-pilot
import pandas as pd

# Create a small DataFrame with duplicate rows
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob'],
    'Age': [25, 30, 25, 35, 30],
    'City': ['NYC', 'LA', 'NYC', 'Chicago', 'LA']
})

print(df)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2    Alice   25      NYC
3  Charlie   35  Chicago
4      Bob   30       LA

In [22]:
df_dup = df.drop_duplicates()
df_dup

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
3  Charlie   35  Chicago

In [25]:
# Create statistics dictionary for aggregation function
statistics = {'Age': 'min'}
df_unique = df_dup.groupby('Name').agg(statistics).reset_index()
df_unique

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [26]:
# Find suplicated values again
duplicates = df.duplicated(subset = ['Name', 'Age', 'City'], keep=False)
duplicates

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [27]:
duplicated_df = df_unique[duplicates == True]
duplicated_df

C:\Users\lorra\AppData\Local\Temp\ipykernel_37544\2222473765.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  duplicated_df = df_unique[duplicates == True]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35