# 3. Series Methods

This chapter covers:
- Importing CSV data sets with the read_csv function
- Sorting Series values in ascending and descending order
- Retrieving the largest and smallest values in a Series
- Counting occurrences of unique values in a Series
- Invoking a function with every value in the Series

In [1]:
import pandas as pd

In [2]:
pd.read_csv("pokemon.csv")

         Pokemon            Type
0      Bulbasaur  Grass / Poison
1        Ivysaur  Grass / Poison
2       Venusaur  Grass / Poison
3     Charmander            Fire
4     Charmeleon            Fire
..           ...             ...
804    Stakataka    Rock / Steel
805  Blacephalon    Fire / Ghost
806      Zeraora        Electric
807       Meltan           Steel
808     Melmetal           Steel

[809 rows x 2 columns]

In [3]:
pd.read_csv("pokemon.csv", index_col = "Pokemon")

                       Type
Pokemon
Bulbasaur    Grass / Poison
Ivysaur      Grass / Poison
Venusaur     Grass / Poison
Charmander             Fire
Charmeleon             Fire
...                     ...
Stakataka      Rock / Steel
Blacephalon    Fire / Ghost
Zeraora            Electric
Meltan                Steel
Melmetal              Steel

[809 rows x 1 columns]

In [4]:
df = pd.read_csv("pokemon.csv", index_col="Pokemon")
pokemon = df.squeeze("columns")
type(pokemon)

pandas.core.series.Series

In [5]:
pd.read_csv("google_stocks.csv").head()

         Date  Close
0  2004-08-19  49.98
1  2004-08-20  53.95
2  2004-08-23  54.50
3  2004-08-24  52.24
4  2004-08-25  52.80

In [6]:
pd.read_csv("google_stocks.csv", parse_dates=["Date"]).head()

        Date  Close
0 2004-08-19  49.98
1 2004-08-20  53.95
2 2004-08-23  54.50
3 2004-08-24  52.24
4 2004-08-25  52.80

In [7]:
df = pd.read_csv("google_stocks.csv", parse_dates = ['Date'], index_col="Date")
google = df.squeeze("columns")
google.head()

Date
2004-08-19    49.98
2004-08-20    53.95
2004-08-23    54.50
2004-08-24    52.24
2004-08-25    52.80
Name: Close, dtype: float64

In [8]:
type(google)

pandas.core.series.Series

In [9]:
pd.read_csv('revolutionary_war.csv').tail()

                         Battle  Start Date     State
227         Siege of Fort Henry   9/11/1782  Virginia
228  Grand Assault on Gibraltar   9/13/1782       NaN
229   Action of 18 October 1782  10/18/1782       NaN
230   Action of 6 December 1782   12/6/1782       NaN
231   Action of 22 January 1783   1/22/1783  Virginia

In [10]:
pd.read_csv('revolutionary_war.csv', index_col='Start Date', parse_dates=['Start Date']).tail()

                                Battle     State
Start Date
1782-09-11         Siege of Fort Henry  Virginia
1782-09-13  Grand Assault on Gibraltar       NaN
1782-10-18   Action of 18 October 1782       NaN
1782-12-06   Action of 6 December 1782       NaN
1783-01-22   Action of 22 January 1783  Virginia

In [11]:
df = pd.read_csv("revolutionary_war.csv", index_col='Start Date', parse_dates=['Start Date'], usecols=["State", "Start Date"])
battles = df.squeeze("columns")

In [12]:
battles.head()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
Name: State, dtype: object

In [13]:
type(battles)

pandas.core.series.Series

In [14]:
google.sort_values()

Date
2004-09-03      49.82
2004-09-01      49.94
2004-08-19      49.98
2004-09-02      50.57
2004-09-07      50.60
               ...
2019-04-23    1264.55
2019-10-25    1265.13
2018-07-26    1268.33
2019-04-26    1272.18
2019-04-29    1287.58
Name: Close, Length: 3824, dtype: float64

In [15]:
pokemon.sort_values()

Pokemon
Illumise                Bug
Silcoon                 Bug
Pinsir                  Bug
Burmy                   Bug
Wurmple                 Bug
                  ...
Tirtouga       Water / Rock
Relicanth      Water / Rock
Corsola        Water / Rock
Carracosta     Water / Rock
Empoleon      Water / Steel
Name: Type, Length: 809, dtype: object

In [16]:
google.sort_values(ascending=False).head()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [17]:
pokemon.sort_values(ascending=False).head()

Pokemon
Empoleon      Water / Steel
Corsola        Water / Rock
Relicanth      Water / Rock
Carracosta     Water / Rock
Tirtouga       Water / Rock
Name: Type, dtype: object

In [18]:
battles.sort_values()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1782-08-08            NaN
1782-08-25            NaN
1782-09-13            NaN
1782-10-18            NaN
1782-12-06            NaN
Name: State, Length: 232, dtype: object

In [19]:
battles.sort_values(na_position="first")

Start Date
1775-09-17         NaN
1775-12-31         NaN
1776-03-03         NaN
1776-03-25         NaN
1776-05-18         NaN
                ...
1781-07-06    Virginia
1781-07-01    Virginia
1781-06-26    Virginia
1781-04-25    Virginia
1783-01-22    Virginia
Name: State, Length: 232, dtype: object

In [21]:
len(battles.sort_values(na_position="first"))

232

In [20]:
battles.dropna().sort_values()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
                 ...
1781-07-06       Virginia
1781-07-01       Virginia
1781-06-26       Virginia
1781-04-25       Virginia
1783-01-22       Virginia
Name: State, Length: 162, dtype: object

In [22]:
len(battles.dropna().sort_values())

162

In [23]:
pokemon.sort_index().head()

Pokemon
Abomasnow      Grass / Ice
Abra               Psychic
Absol                 Dark
Accelgor               Bug
Aegislash    Steel / Ghost
Name: Type, dtype: object

In [25]:
battles.sort_index()

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
1775-04-19    Massachusetts
1775-04-20         Virginia
                  ...
1783-01-22         Virginia
NaT              New Jersey
NaT                Virginia
NaT                     NaN
NaT                     NaN
Name: State, Length: 232, dtype: object

In [26]:
battles.sort_index(ascending = False).head()

Start Date
1783-01-22    Virginia
1782-12-06         NaN
1782-10-18         NaN
1782-09-13         NaN
1782-09-11    Virginia
Name: State, dtype: object

In [27]:
google.sort_values(ascending = False).head()

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [28]:
google.nlargest(5)

Date
2019-04-29    1287.58
2019-04-26    1272.18
2018-07-26    1268.33
2019-10-25    1265.13
2019-04-23    1264.55
Name: Close, dtype: float64

In [30]:
google.nsmallest(n=5)

Date
2004-09-03    49.82
2004-09-01    49.94
2004-08-19    49.98
2004-09-02    50.57
2004-09-07    50.60
Name: Close, dtype: float64

In [31]:
battles.head(3)

Start Date
1774-09-01    Massachusetts
1774-12-14    New Hampshire
1775-04-19    Massachusetts
Name: State, dtype: object

In [33]:
battles = battles.sort_values()

In [34]:
battles.head(3)

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
Name: State, dtype: object

In [35]:
pokemon.head()

Pokemon
Bulbasaur     Grass / Poison
Ivysaur       Grass / Poison
Venusaur      Grass / Poison
Charmander              Fire
Charmeleon              Fire
Name: Type, dtype: object

In [36]:
pokemon.value_counts()

Type
Normal              65
Water               61
Grass               38
Psychic             35
Fire                30
                    ..
Normal / Dragon      1
Psychic / Steel      1
Rock / Poison        1
Fighting / Ghost     1
Fire / Ghost         1
Name: count, Length: 159, dtype: int64

In [37]:
len(pokemon.value_counts())

159

In [38]:
pokemon.nunique()

159

In [39]:
pokemon.value_counts(ascending=True)

Type
Steel / Ground      1
Fire / Rock         1
Rock / Dark         1
Psychic / Grass     1
Fire / Steel        1
                   ..
Fire               30
Psychic            35
Grass              38
Water              61
Normal             65
Name: count, Length: 159, dtype: int64

In [40]:
pokemon.value_counts(normalize=True).head() * 100

Type
Normal     8.034611
Water      7.540173
Grass      4.697157
Psychic    4.326329
Fire       3.708282
Name: proportion, dtype: float64

In [41]:
(pokemon.value_counts(normalize=True) * 100).sum()

np.float64(99.99999999999999)

In [42]:
(pokemon.value_counts(normalize=True) * 100).round(2)

Type
Normal              8.03
Water               7.54
Grass               4.70
Psychic             4.33
Fire                3.71
                    ...
Normal / Dragon     0.12
Psychic / Steel     0.12
Rock / Poison       0.12
Fighting / Ghost    0.12
Fire / Ghost        0.12
Name: proportion, Length: 159, dtype: float64

In [43]:
google.value_counts().head()

Close
307.10    3
237.04    3
194.27    3
288.92    3
290.41    3
Name: count, dtype: int64

In [44]:
google.max()

np.float64(1287.58)

In [45]:
google.min()

np.float64(49.82)

In [46]:
buckets = [0, 200, 400, 600, 800, 1000, 1200, 1400]
google.value_counts(bins=buckets)

(200.0, 400.0]      1568
(-0.001, 200.0]      595
(400.0, 600.0]       575
(1000.0, 1200.0]     406
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [47]:
google.value_counts(bins=buckets).sort_index()

(-0.001, 200.0]      595
(200.0, 400.0]      1568
(400.0, 600.0]       575
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1000.0, 1200.0]     406
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [48]:
google.value_counts(bins=buckets, sort=False)

(-0.001, 200.0]      595
(200.0, 400.0]      1568
(400.0, 600.0]       575
(600.0, 800.0]       380
(800.0, 1000.0]      207
(1000.0, 1200.0]     406
(1200.0, 1400.0]      93
Name: count, dtype: int64

In [49]:
google.value_counts(bins=6, sort=False)

(48.581, 256.113]      1204
(256.113, 462.407]     1104
(462.407, 668.7]        507
(668.7, 874.993]        380
(874.993, 1081.287]     292
(1081.287, 1287.58]     337
Name: count, dtype: int64

In [50]:
battles.head()

Start Date
1781-09-06    Connecticut
1779-07-05    Connecticut
1777-04-27    Connecticut
1777-09-03       Delaware
1777-05-17        Florida
Name: State, dtype: object

In [51]:
battles.value_counts().head()

State
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Massachusetts     11
Name: count, dtype: int64

In [52]:
battles.value_counts(dropna=False).head()

State
NaN               70
South Carolina    31
New York          28
New Jersey        24
Virginia          21
Name: count, dtype: int64

In [54]:
battles.index

DatetimeIndex(['1781-09-06', '1779-07-05', '1777-04-27', '1777-09-03',
               '1777-05-17', '1779-09-10', '1779-09-07', '1780-03-02',
               '1778-06-30', '1781-01-07',
               ...
               '1782-05-06', '1782-05-25', '1782-05-28', '1782-07-01',
               '1782-07-06', '1782-08-08', '1782-08-25', '1782-09-13',
               '1782-10-18', '1782-12-06'],
              dtype='datetime64[ns]', name='Start Date', length=232, freq=None)

In [55]:
battles.index.value_counts()

Start Date
1781-05-22    2
1780-05-25    2
1775-04-19    2
1777-08-22    2
1778-09-07    2
             ..
1782-08-08    1
1782-08-25    1
1782-09-13    1
1782-10-18    1
1782-12-06    1
Name: count, Length: 217, dtype: int64

In [56]:
funcs = [len, max, min]

In [57]:
for current_func in funcs:
    print(current_func(google))

3824
1287.58
49.82

In [58]:
round(99.2)

99

In [59]:
round(99.49)

99

In [60]:
round(99.5)

100

In [62]:
google.apply(func=round)

Date
2004-08-19      50
2004-08-20      54
2004-08-23      54
2004-08-24      52
2004-08-25      53
              ...
2019-10-21    1246
2019-10-22    1243
2019-10-23    1259
2019-10-24    1261
2019-10-25    1265
Name: Close, Length: 3824, dtype: int64

In [64]:
def single_or_multi(pokemon_type):
    if "/" in pokemon_type:
        return "Multi"
    return "Single"

In [65]:
pokemon.head()

Pokemon
Bulbasaur     Grass / Poison
Ivysaur       Grass / Poison
Venusaur      Grass / Poison
Charmander              Fire
Charmeleon              Fire
Name: Type, dtype: object

In [66]:
pokemon.apply(single_or_multi)

Pokemon
Bulbasaur       Multi
Ivysaur         Multi
Venusaur        Multi
Charmander     Single
Charmeleon     Single
                ...
Stakataka       Multi
Blacephalon     Multi
Zeraora        Single
Meltan         Single
Melmetal       Single
Name: Type, Length: 809, dtype: object

In [67]:
pokemon.apply(single_or_multi).value_counts()

Type
Multi     405
Single    404
Name: count, dtype: int64