# Data Extraction

In [1]:
# import the key modules
import numpy as np
import pandas as pd

# 1. First Look at Dataset Setting Index and Selecting Columns

In [2]:
# read csv file
df = pd.read_csv('players_20.csv')
df.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [3]:
df.set_index("short_name", inplace=True)

In [4]:
df.head()

,sofifa_id,player_url,long_name,age,dob,height_cm,weight_kg,nationality,club,overall,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
short_name,,,,,,,,,,,,,,,,,,,,,
L. Messi,158023,https://sofifa.com/player/158023/lionel-messi/...,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,94,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
Cristiano Ronaldo,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,93,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
Neymar Jr,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,92,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
J. Oblak,200389,https://sofifa.com/player/200389/jan-oblak/20/...,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E. Hazard,183277,https://sofifa.com/player/183277/eden-hazard/2...,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,91,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [5]:
# select columns
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [6]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# 2. Selecting elements by index label with .loc()

## 2.1 Selecting with a single value

loc[row_label, column_label]

In [7]:
# get all data about 'L. Messi' 
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [8]:
type(df.loc['L. Messi'])

pandas.core.series.Series

In [9]:
df.loc['L. Messi']['long_name']

'Lionel Andrés Messi Cuccittini'

In [10]:
df.loc['L. Messi'].index

Index(['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality',
       'club'],
      dtype='object')

In [11]:
# get the height of 'L. Messi'
df.loc['L. Messi', 'height_cm']

np.int64(170)

In [12]:
# get the weight of 'Cristiano Ronaldo'
df.loc['Cristiano Ronaldo', 'weight_kg']

np.int64(83)

In [13]:
# get all rows inside the 'height_cm' column
df.loc[:, 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [14]:
# get all columns that correspond to the index 'L. Messi'

In [15]:
df.loc['L. Messi', :]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [16]:
df.loc['L. Messi', ['long_name', 'age']]

long_name    Lionel Andrés Messi Cuccittini
age                                      32
Name: L. Messi, dtype: object

## 2.2 Selecting with a list of values

In [17]:
# get all data about 'L. Messi' and 'Cristiano Ronaldo'
df.loc[['L. Messi', 'Cristiano Ronaldo']]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [18]:
# get all height of 'L. Messi' and 'Cristiano Ronaldo'
df.loc[['L. Messi', 'Cristiano Ronaldo'], 'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [19]:
df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm']]

                   height_cm
short_name
L. Messi                 170
Cristiano Ronaldo        187

In [20]:
# get the height and weight of 'L. Messi' 
df.loc['L. Messi', ['height_cm', 'weight_kg']]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [21]:
df.loc[['L. Messi'], ['height_cm', 'weight_kg']]

            height_cm  weight_kg
short_name
L. Messi          170         72

In [22]:
# get height and weight of 'L. Messi' and 'Cristiano Ronaldo'
df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm', 'weight_kg']]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

## 2.3 Selecting a range of data with a slice

start:stop:step (Note that contrary to usual python slices, both the start and the stop are included)

In [23]:
# slice column labels
players = ['L. Messi', 'Cristiano Ronaldo']
df.loc[players, 'age':'club']

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [24]:
# slice index labels
columns = ['age', 'dob', 'height_cm', 'weight_kg']

# get top 1 and top10 player names
df.index[:10]
df.loc['L. Messi':'M. Salah']

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool

In [25]:
df.loc[df.index[:10]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
L. Modrić,Luka Modrić,33,1985-09-09,172,66,Croatia,Real Madrid
M. Salah,Mohamed Salah Ghaly,27,1992-06-15,175,71,Egypt,Liverpool

## 2.4 Selecting with conditions

In [26]:
# one condition: select player with height above 180 cm
columns = ['age', 'dob', 'height_cm', 'weight_kg']
df.loc[df['height_cm'] > 180, columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [27]:
# multiple conditions: select player with height above 180cm from Argentina
df.loc[(df['height_cm'] > 180) & (df['nationality']=='Argentina'),:]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors

# 3. Selecting elements by index position with iloc()

In [28]:
# set up df from scratch
df = pd.read_csv('players_20.csv')

# set index
df.set_index('short_name', inplace=True)

# select columns
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

## 3.1 Selecting with a single value

iloc[row_position, column_position]

In [29]:
# get the height of L. Messi
df.iloc[0, 3]

np.int64(170)

In [30]:
# get the weight of Cristiano Ronaldo
df.iloc[1, 4]

np.int64(83)

In [31]:
# get all rows inside the 'height_cm' colulmn
df.iloc[:,3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [32]:
# get all columns that correspond to the index 'L. Messi'
df.iloc[0,:]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

## 3.2 Selecting with a list of values

In [39]:
# get all data about 'L. Messi' and 'Cristiano Ronaldo'
df.iloc[[0,1]]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus

In [40]:
# get the height of 'L. Messi' and 'Cristiano Ronaldo'
df.iloc[[0,1], 3]

short_name
L. Messi             170
Cristiano Ronaldo    187
Name: height_cm, dtype: int64

In [41]:
# get the height and weight of 'L. Messi'
df.iloc[0, [3,4]]

height_cm    170
weight_kg     72
Name: L. Messi, dtype: object

In [42]:
# get the height and weight of 'L. Messi' and 'Cristiano Ronaldo'
df.iloc[[0,1], [3,4]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83

## 3.3 Selecting a range of data with a slice

start:stop (Note: start in included by the stop is excluded.)

In [47]:
# slice column labels age/club
# players = ['L. Messi' and 'Cristiano Ronaldo']
players = [0,1]
df.iloc[players, 1:7]

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
L. Messi,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,34,1985-02-05,187,83,Portugal,Juventus

In [50]:
# slice index labels (top1 to top10 player)
# columns ['age', 'dob', 'height_cm', 'weight_kg']
columns = [1,2,3,4]

# get top1 and top10 player name
df.iloc[0:10, columns]

                   age         dob  height_cm  weight_kg
short_name
L. Messi            32  1987-06-24        170         72
Cristiano Ronaldo   34  1985-02-05        187         83
Neymar Jr           27  1992-02-05        175         68
J. Oblak            26  1993-01-07        188         87
E. Hazard           28  1991-01-07        175         74
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
L. Modrić           33  1985-09-09        172         66
M. Salah            27  1992-06-15        175         71

## 3.4 Selecting with conditions

iloc cannot accept a boolean Series, but only a boolean list. We have to use the list() function to convert a Series into a boolean list.

In [54]:
# one condition: select player with height above 180cm
# columns = ['age', 'dob', 'height_cm', 'weight_kg']
columns = [1,2,3,4]

#list(df['height_cm']>180)

df.iloc[list(df['height_cm']>180), columns]

                   age         dob  height_cm  weight_kg
short_name
Cristiano Ronaldo   34  1985-02-05        187         83
J. Oblak            26  1993-01-07        188         87
K. De Bruyne        28  1991-06-28        181         70
M. ter Stegen       27  1992-04-30        187         85
V. van Dijk         27  1991-07-08        193         92
...                ...         ...        ...        ...
P. Martin           20  1999-01-05        188         84
Shao Shuai          22  1997-03-10        186         79
Zhang Wei           19  2000-05-16        186         75
Wang Haijian        18  2000-08-02        185         74
Pan Ximing          26  1993-01-11        182         78

[9744 rows x 4 columns]

In [55]:
# multiple conditions: select player with height above 180cm and from Argentina
# list( (df['height_cm']>180) & (df['nationality']=="Argentina") )

df.iloc[list( (df['height_cm']>180) & (df['nationality']=="Argentina") ), :]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Icardi,Mauro Emanuel Icardi Rivero,26,1993-02-19,181,75,Argentina,Inter
G. Higuaín,Gonzalo Gerardo Higuaín,31,1987-12-10,186,89,Argentina,Juventus
E. Garay,Ezequiel Marcelo Garay,32,1986-10-10,189,90,Argentina,Valencia CF
N. Otamendi,Nicolás Hernán Otamendi,31,1988-02-12,183,81,Argentina,Manchester City
G. Rulli,Gerónimo Rulli,27,1992-05-20,189,84,Argentina,Montpellier HSC
...,...,...,...,...,...,...,...
T. Durso,Tomás Durso,20,1999-02-26,185,80,Argentina,Gimnasia y Esgrima La Plata
J. Hass,Joaquín Hass,21,1998-03-27,186,88,Argentina,Club Atlético Colón
R. Ferrario,Rafael Ferrario,19,2000-04-30,186,76,Argentina,Club Atlético Huracán
L. Finochietto,Leandro Finochietto,22,1997-04-25,186,77,Argentina,Argentinos Juniors
N. Forastiero,Nicolás Forastiero,20,1998-07-16,182,79,Argentina,Argentinos Juniors

# 4. Set New Value for a Cell in a DataFrame

## 4.1 Set value to one cell

In [58]:
# update L. Messi height
df.loc['L. Messi', 'height_cm'] = 175

In [59]:
# show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

## 4.2 Set value of entire column

In [65]:
# set height of all players to 190
df.loc[:, 'height_cm'] = 190

In [66]:
# show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid

## 4.3 Set value to entire row

In [70]:
# get all columns that correspond to player ranked last in fifa
df.iloc[-1]

long_name                         潘喜明
age                                26
dob                        1993-01-11
height_cm                         190
weight_kg                          78
nationality                  China PR
club           Hebei China Fortune FC
Name: Pan Ximing, dtype: object

In [72]:
# set null values to all columns that corresponds to player ranked last
import numpy as np

df.iloc[-1, :] = np.nan

In [73]:
# show dataframe
df.iloc[-1]

long_name      NaN
age            NaN
dob            NaN
height_cm      NaN
weight_kg      NaN
nationality    NaN
club           NaN
Name: Pan Ximing, dtype: object

In [74]:
df.tail(4)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,190.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,190.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,190.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 4.4 Set value to multiple cells

In [79]:
# set value for all items matching the list of labels
['L. Messi', 'Cristiano Ronaldo']
df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm']] = 175

In [80]:
# show dataframe
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,190.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,190.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,190.0,74.0,Belgium,Real Madrid

## 4.5 Set value for rows matching a condition

In [82]:
# set value for rows matching a condition
columns = ['age', 'dob', 'height_cm', 'weight_kg']

df.loc[df['height_cm'] > 180, columns] = 0

In [77]:
# show dataframe

In [83]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,0.0,0,0.0,0.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid

# 5.Drop Rows Or Columns from a Dataframe

In [84]:
# restore the dataframe
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

## 5.1 Drop Row

In [88]:
# drop one row
# axis parameter
#df.drop('L. Messi', axis=0)

# index parameter
df.drop(index=['L. Messi'])

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [89]:
# drop two or more rows and update data (inplace=True)
df.drop(['L. Messi', 'Cristiano Ronaldo' ], axis=0, inplace=True)

In [90]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona

## 5.2 Drop Columns

In [96]:
# drop one column
# axis parameter

#df.drop('long_name', axis=1)


# column parameter
df.drop(columns=['long_name'])

,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,
Neymar Jr,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...
Shao Shuai,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [99]:
# drop column by position/index (drop last column)
df.columns[[-1]]

df.drop(df.columns[[-1]], axis=1)

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany
...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR
Zhang Wei,张威,19,2000-05-16,186,75,China PR
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR

In [101]:
# drop two or more columns and update data (inplace=True)
df.drop(['long_name', 'dob'], axis=1, inplace=True)

In [102]:
df.head()

               age  height_cm  weight_kg nationality                 club
short_name
Neymar Jr       27        175         68      Brazil  Paris Saint-Germain
J. Oblak        26        188         87    Slovenia      Atlético Madrid
E. Hazard       28        175         74     Belgium          Real Madrid
K. De Bruyne    28        181         70     Belgium      Manchester City
M. ter Stegen   27        187         85     Germany         FC Barcelona

# 6.Create Random Sample with the sample() Method

In [103]:
# restore the dataframe
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [104]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

## 6.1 sample()

In [111]:
# extract 10 random elements from the "nationality" column
df['nationality'].sample(n=10, random_state=99)

short_name
R. Alvarado               Mexico
Qiao Wei                China PR
E. Paredes                 Chile
K. Stoyanov             Bulgaria
M. Chudý                Slovakia
D. Sundaram                India
R. Gagliardini             Italy
G. Debeljuh              Croatia
Kim Seung Yong    Korea Republic
M. Hansen                Denmark
Name: nationality, dtype: object

In [115]:
# extract a random 20% sample of the dataframe
df.sample(frac=0.2, random_state=12)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Y. Thoelen,Yannick Thoelen,28,1990-07-18,188,89,Belgium,KV Mechelen
M. Nadé,Mickaël Nadé,20,1999-03-04,188,80,France,AS Saint-Étienne
V. García,Víctor Hugo García Hernández,25,1994-06-11,178,71,Venezuela,Vitória Guimarães
M. Gyamfi,Maxwell Gyamfi,19,2000-01-18,185,75,Germany,VfL Bochum 1848
W. Cyprien,Wylan Cyprien,24,1995-01-28,180,75,France,OGC Nice
...,...,...,...,...,...,...,...
H. Kadish,Hassan Kadish,26,1992-09-26,179,73,Saudi Arabia,Al Hilal
A. Chapman,Aaron Chapman,29,1990-05-29,203,92,England,Peterborough United
I. Ezekiel,Imoh Ezekiel,25,1993-10-24,178,70,Nigeria,KV Kortrijk
H. Sakai,酒井 宏樹,29,1990-04-12,183,70,Japan,Olympique de Marseille
C. Keșerü,Claudiu Andrei Keșerü,32,1986-12-02,178,71,Romania,Romania

In [117]:
# unsample: increase the sampling rate -> frac>1 (Note: replace parameter > 1)
df.sample(frac=2, replace=True, random_state = 99)

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
M. Hauptmeijer,Mike Hauptmeijer,22,1997-03-18,191,70,Netherlands,PEC Zwolle
A. Mosquera,Andrés Mosquera,29,1990-02-20,182,80,Colombia,Club León
V. Thill,Vincent Thill,19,2000-02-04,172,58,Luxembourg,US Orléans Loiret Football
D. Bouanga,Denis Bouanga,24,1994-11-11,180,70,Gabon,AS Saint-Étienne
S. Al Selouli,Saad Al Selouli,21,1998-05-25,168,57,Saudi Arabia,Ettifaq FC
...,...,...,...,...,...,...,...
M. Connor,Matthew Connor,22,1997-04-08,192,82,Republic of Ireland,Waterford FC
J. Northcott,Jordan Northcott,17,2002-02-09,162,60,Scotland,St. Johnstone FC
A. Bodzek,Adam Bodzek,33,1985-09-07,184,81,Poland,Fortuna Düsseldorf
J. Adebayo-Smith,Jordan Adebayo-Smith,18,2001-01-11,181,77,United States,Lincoln City
F. Mac Allister,Francis Manuel Mac Allister,23,1995-10-30,176,71,Argentina,Argentinos Juniors

# 7. Filter A DataFrame with the query() method

In [118]:
# restore the dataframe information
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

## 7.1 query()

In [120]:
# select players older than 34
df.query("age>34")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
...,...,...,...,...,...,...,...
N. Hunt,Nicky Hunt,35,1983-09-03,185,86,England,Crewe Alexandra
K. Ogi,荻 晃太,36,1983-05-05,185,76,Japan,Vissel Kobe
J. McCombe,Jamie McCombe,36,1983-01-01,196,79,England,Lincoln City
G. Maley,Gary Maley,36,1982-08-03,188,90,Scotland,Livingston FC
Zhou Ting,周挺,40,1979-02-05,182,73,China PR,Dalian YiFang FC

In [123]:
# exercise: write the equivalent boolean slicing
df[df['age'] > 34].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Z. Ibrahimović,Zlatan Ibrahimović,37,1981-10-03,195,95,Sweden,LA Galaxy
Pepe,Képler Laveran Lima Ferreira,36,1983-02-26,188,81,Portugal,FC Porto
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
Casillas,Iker Casillas Fernández,38,1981-05-20,185,84,Spain,FC Porto
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria

In [131]:
# select players older than 34 form Italy
df.query("age>34 and nationality=='Italy'")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC
C. Maggio,Christian Maggio,37,1982-02-11,184,79,Italy,Benevento
D. Dainelli,Dario Dainelli,40,1979-06-09,191,78,Italy,Livorno
F. Marchetti,Federico Marchetti,36,1983-02-07,188,83,Italy,Genoa
F. Peluso,Federico Peluso,35,1984-01-20,188,82,Italy,Sassuolo
C. Terzi,Claudio Terzi,35,1984-06-19,180,69,Italy,Spezia
A. Rosina,Alessandro Rosina,35,1984-01-31,170,69,Italy,US Salernitana 1919
D. Maietta,Domenico Maietta,36,1982-08-03,184,75,Italy,Empoli
A. Cordaz,Alex Cordaz,36,1983-01-01,188,83,Italy,Crotone
S. Floccari,Sergio Floccari,37,1981-11-12,180,79,Italy,SPAL
M. Iori,Manuel Iori,37,1982-03-12,182,72,Italy,Cittadella
M. Stefani,Mirco Stefani,35,1984-01-25,180,80,Italy,Pordenone
G. Pegolo,Gianluca Pegolo,38,1981-03-25,183,76,Italy,Sassuolo
D. Gastaldello,Daniele Gastaldello,36,1983-06-25,185,77,Italy,Brescia
D. Moscardelli,Davide Moscardelli,39,1980-02-03,185,80,Italy,Pisa
E. Calaiò,Emanuele Calaiò,37,1982-01-08,179,75,Italy,US Salernitana 1919
D. Croce,Daniele Croce,36,1982-09-09,173,70,Italy,US Cremonese
A. Rosati,Antonio Rosati,36,1983-06-26,195,88,Italy,Torino
F. Mazzeo,Fabio Mazzeo,35,1983-07-24,177,77,Italy,Livorno
M. De Agostini,Michele De Agostini,35,1983-11-27,180,78,Italy,Pordenone
A. Pomini,Alberto Pomini,38,1981-03-17,185,80,Italy,Venezia FC
F. Evacuo,Felice Evacuo,36,1982-08-23,187,88,Italy,Trapani
G. Munari,Gianni Munari,36,1983-06-24,190,84,Italy,Parma
L. Pagliarulo,Luca Pagliarulo,35,1984-02-29,187,80,Italy,Trapani
C. Del Grosso,Cristiano Del Grosso,36,1983-03-24,171,66,Italy,Pescara
R. Vitiello,Roberto Vitiello,36,1983-05-08,176,72,Italy,Castellammare di Stabia
A. Bruno,Alessandro Bruno,35,1983-07-04,180,70,Italy,Pescara
T. Berni,Tommaso Berni,36,1983-03-06,185,80,Italy,Inter
P. Gori,Pier Graziano Gori,39,1980-05-10,189,83,Italy,Benevento
S. Farelli,Simone Farelli,36,1983-02-19,186,82,Italy,Pescara

In [132]:
# exercise: write the equivalent boolean slicing
df[(df['age'] > 34) & (df['nationality'] == 'Italy')].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
G. Buffon,Gianluigi Buffon,41,1978-01-28,192,92,Italy,Juventus
F. Quagliarella,Fabio Quagliarella,36,1983-01-31,180,79,Italy,Sampdoria
D. De Rossi,Daniele De Rossi,35,1983-07-24,184,83,Italy,Boca Juniors
A. Mirante,Antonio Mirante,35,1983-07-08,193,79,Italy,Roma
A. Diamanti,Alessandro Diamanti,36,1983-05-02,180,75,Italy,Western United FC

In [134]:
# add a not operator to the first example
df.query("not (age>34)")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [136]:
# exercise: write the equivalent using boolean slicing
df[~(df['age'] > 34)].head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

In [137]:
# convert height to meters and select those with height above 1.8
df.query("(height_cm / 100) > 1.8")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [138]:
# exercise: write the equivalent using boolean slicing
df[ (df["height_cm"] / 100) > 1.8]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
V. van Dijk,Virgil van Dijk,27,1991-07-08,193,92,Netherlands,Liverpool
...,...,...,...,...,...,...,...
P. Martin,Paul Martin,20,1999-01-05,188,84,Republic of Ireland,Waterford FC
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [144]:
# select players that wer born after 1990

# check out data type
df.dtypes
# convert "dob" column to datetime type
df['dob'] = df['dob'].astype('datetime64[ns]')

# query
df.query("dob.dt.year > 1990")

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [145]:
# exercise: write the equivalent using boolean slicing
df[ df["dob"].dt.year > 1990]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC