In [1]:
import pandas as pd
import numpy as np

# Creating a dataframe from an array

## Option 1

In [2]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])
data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
pd.DataFrame(data)

   0  1
0  1  4
1  2  5
2  3  6

In [4]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])
# showing a dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

## Option 2

In [5]:
# creating an array with list shape
data = [[1,4], [2,5], [3,6]]
data

[[1, 4], [2, 5], [3, 6]]

In [6]:
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])
# showing a dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

# Creating a DataFrame from a dictionary

In [7]:
# lists used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [39613493, 29730311, 21944577, 19299981]

In [8]:
# Storing lists within a dictionary
z = zip(states, population)
for i,v in z:
    print(i, " ", v)

California   39613493
Texas   29730311
Florida   21944577
New York   19299981

In [9]:
[{'state': i, 'population': v} for i,v in zip(states, population)]

[{'state': 'California', 'population': 39613493},
 {'state': 'Texas', 'population': 29730311},
 {'state': 'Florida', 'population': 21944577},
 {'state': 'New York', 'population': 19299981}]

In [10]:
# Storing lists within a dictionary
dict_states = { 'States': states, 'Population': population}
dict_states

{'States': ['California', 'Texas', 'Florida', 'New York'],
 'Population': [39613493, 29730311, 21944577, 19299981]}

In [11]:
# Creating the dataframe
df_population = pd.DataFrame(dict_states)

In [12]:
# showing the dataframe
df_population

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

In [18]:
my_population_state = [{"States": "California", "Population": 39613493 },
                       {"States": "Texas", "Population": 29730311 },
                       {"States": "Florida", "Population": 21944577 },
                       {"States": "New York", "Population": 19299981 }]
my_population_state

[{'States': 'California', 'Population': 39613493},
 {'States': 'Texas', 'Population': 29730311},
 {'States': 'Florida', 'Population': 21944577},
 {'States': 'New York', 'Population': 19299981}]

In [19]:
df_population2 = pd.DataFrame(my_population_state)
df_population2

       States  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

# Creating a DataFrame from a csv file

In [13]:
# reading the csv file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [14]:
# show first 5 rows of dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [15]:
# show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [20]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [22]:
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

# 3. Basic Attributes, Methods and Functions

In [24]:
df_exams.shape

(1000, 8)

In [25]:
# getting access to the index attributes
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [26]:
# getting access to the columns attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [27]:
# data types of each column
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [28]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# 2. Methods

In [32]:
# showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [33]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [34]:
# describing statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# 3. Functions

In [40]:
# obtaining the length of the dataframe (number of rows)
len(df_exams)

1000

In [42]:
# obtaining the highest index of the dataframe
max(df_exams.index)

999

In [44]:
# obtaining the lowest index of the data frame
min(df_exams.index)

0

In [38]:
# obtaining the data type

In [46]:
type(df_exams)

pandas.core.frame.DataFrame